factory_method::FactoryGenerator
Generator factory_method.FactoryGenerator.generator
Referenced by factory_method.FactoryGenerator.createGenerator.
Generator factory_method.FactoryGenerator.createGenerator(GeneratorType generatorType)
createGenerator - Creates an instance of Generator based on the provided GeneratorType.
generatorType returns an instance of Generator
References factory_method.FactoryGenerator.generator, factory_method.FactoryLoader.getInstance.
Referenced by metaheuristics.generators.MultiGenerator.initializeGenerators, metaheuristics.generators.InstanceDE.run, metaheuristics.generators.InstanceEE.run, metaheuristics.generators.InstanceGA.run.