metaheuristics::generators::MultiobjectiveHillClimbingDistance
CandidateValue metaheuristics.generators.MultiobjectiveHillClimbingDistance.candidatevalue
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.generate.
AcceptType metaheuristics.generators.MultiobjectiveHillClimbingDistance.typeAcceptation
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference.
StrategyType metaheuristics.generators.MultiobjectiveHillClimbingDistance.strategy
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.generate.
CandidateType metaheuristics.generators.MultiobjectiveHillClimbingDistance.typeCandidate
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.generate.
State metaheuristics.generators.MultiobjectiveHillClimbingDistance.stateReferenceHC
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.generate, metaheuristics.generators.MultiobjectiveHillClimbingDistance.getReference, metaheuristics.generators.MultiobjectiveHillClimbingDistance.getReferenceList, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference.
IFFactoryAcceptCandidate metaheuristics.generators.MultiobjectiveHillClimbingDistance.ifacceptCandidate
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference.
GeneratorType metaheuristics.generators.MultiobjectiveHillClimbingDistance.generatortype
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.getGeneratorType, metaheuristics.generators.MultiobjectiveHillClimbingDistance.setGeneratorType.
List<State> metaheuristics.generators.MultiobjectiveHillClimbingDistance.listStateReference
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.getReferenceList.
float metaheuristics.generators.MultiobjectiveHillClimbingDistance.weight
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.MultiobjectiveHillClimbingDistance, metaheuristics.generators.MultiobjectiveHillClimbingDistance.setWeight.
List<Float> metaheuristics.generators.MultiobjectiveHillClimbingDistance.listTrace
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.MultiobjectiveHillClimbingDistance.
List<State> metaheuristics.generators.MultiobjectiveHillClimbingDistance.visitedState
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.contain, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference.
final int metaheuristics.generators.MultiobjectiveHillClimbingDistance.sizeNeighbors
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.getSizeNeighbors.
List<Double> metaheuristics.generators.MultiobjectiveHillClimbingDistance.distanceSolution
static int metaheuristics.generators.MultiobjectiveHillClimbingDistance.getSizeNeighbors()
Accessor for sizeNeighbors.
References metaheuristics.generators.MultiobjectiveHillClimbingDistance.sizeNeighbors.
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference.
static List< Double > metaheuristics.generators.MultiobjectiveHillClimbingDistance.distanceCalculateAdd(List< State > solution)
References problem.definition.State.Distance.
Referenced by local_search.acceptation_type.Dominance.listDominance.
metaheuristics.generators.MultiobjectiveHillClimbingDistance.MultiobjectiveHillClimbingDistance()
MultiobjectiveHillClimbingDistance - class that implements the Multiobjective Hill Climbing Distance metaheuristic.
References local_search.acceptation_type.AcceptType.AcceptNotDominated, metaheuristics.generators.MultiobjectiveHillClimbingDistance.listTrace, metaheuristics.generators.GeneratorType.MultiobjectiveHillClimbingDistance, local_search.complement.StrategyType.NORMAL, local_search.candidate_type.CandidateType.NotDominatedCandidate, metaheuristics.generators.MultiobjectiveHillClimbingDistance.weight.
State metaheuristics.generators.MultiobjectiveHillClimbingDistance.generate(Integer operatornumber)
generate - generate a new state based on the operator number.
operatornumber the operator number to use for generating the state the generated state
References metaheuristics.generators.MultiobjectiveHillClimbingDistance.candidatevalue, problem.definition.Operator.generatedNewState, problem.definition.Problem.getOperator, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.MultiobjectiveHillClimbingDistance.stateReferenceHC, metaheuristics.generators.MultiobjectiveHillClimbingDistance.strategy, metaheuristics.generators.MultiobjectiveHillClimbingDistance.typeCandidate.
void metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference(State stateCandidate, Integer countIterationsCurrent)
updateReference - update the reference state and the list of visited states.
stateCandidate countIterationsCurrent IllegalArgumentException SecurityException ClassNotFoundException InstantiationException IllegalAccessException InvocationTargetException NoSuchMethodException
References local_search.acceptation_type.AcceptableCandidate.acceptCandidate, problem.definition.State.clone, metaheuristics.generators.MultiobjectiveHillClimbingDistance.contain, problem.definition.Problem.Evaluate, problem.definition.Operator.generatedNewState, problem.definition.Operator.generateRandomState, problem.definition.Problem.getOperator, metaheurictics.strategy.Strategy.getProblem, metaheuristics.generators.MultiobjectiveHillClimbingDistance.getReferenceList, metaheuristics.generators.MultiobjectiveHillClimbingDistance.getSizeNeighbors, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.MultiobjectiveHillClimbingDistance.ifacceptCandidate, metaheurictics.strategy.Strategy.listRefPoblacFinal, metaheuristics.generators.MultiobjectiveHillClimbingDistance.solutionMoreDistance, metaheuristics.generators.MultiobjectiveHillClimbingDistance.stateReferenceHC, metaheuristics.generators.MultiobjectiveHillClimbingDistance.typeAcceptation, metaheuristics.generators.MultiobjectiveHillClimbingDistance.visitedState.
List< State > metaheuristics.generators.MultiobjectiveHillClimbingDistance.getReferenceList()
getReferenceList - get the list of reference states.
the list of reference states
References metaheuristics.generators.MultiobjectiveHillClimbingDistance.listStateReference, metaheuristics.generators.MultiobjectiveHillClimbingDistance.stateReferenceHC.
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference.
State metaheuristics.generators.MultiobjectiveHillClimbingDistance.getReference()
getReference - get the reference state.
the reference state
References metaheuristics.generators.MultiobjectiveHillClimbingDistance.stateReferenceHC.
void metaheuristics.generators.MultiobjectiveHillClimbingDistance.setStateRef(State stateRef)
setStateRef - set the reference state.
stateRef the reference state to set
void metaheuristics.generators.MultiobjectiveHillClimbingDistance.setInitialReference(State stateInitialRef)
setInitialReference - set the initial reference state.
stateInitialRef the initial reference state to set
GeneratorType metaheuristics.generators.MultiobjectiveHillClimbingDistance.getGeneratorType()
getGeneratorType - get the generator type.
the generator type
References metaheuristics.generators.MultiobjectiveHillClimbingDistance.generatortype.
void metaheuristics.generators.MultiobjectiveHillClimbingDistance.setGeneratorType(GeneratorType generatortype)
setGeneratorType - set the generator type.
generatortype the generator type to set
References metaheuristics.generators.MultiobjectiveHillClimbingDistance.generatortype.
GeneratorType metaheuristics.generators.MultiobjectiveHillClimbingDistance.getType()
getType - get the generator type.
the generator type
List< State > metaheuristics.generators.MultiobjectiveHillClimbingDistance.getSonList()
getSonList - get the list of child states.
the list of child states
boolean metaheuristics.generators.MultiobjectiveHillClimbingDistance.awardUpdateREF(State stateCandidate)
awardUpdateREF - check if the candidate state should update the reference state.
stateCandidate return true if the reference state should be updated, false otherwise
float metaheuristics.generators.MultiobjectiveHillClimbingDistance.getWeight()
getWeight - get the weight of the generator.
the weight of the generator
void metaheuristics.generators.MultiobjectiveHillClimbingDistance.setWeight(float weight)
setWeight - set the weight of the generator.
weight
References metaheuristics.generators.MultiobjectiveHillClimbingDistance.weight.
int[] metaheuristics.generators.MultiobjectiveHillClimbingDistance.getListCountBetterGender()
getListCountBetterGender - get the list of counts for better gender.
the list of counts for better gender
int[] metaheuristics.generators.MultiobjectiveHillClimbingDistance.getListCountGender()
getListCountGender - get the list of counts for gender.
the list of counts for gender
float[] metaheuristics.generators.MultiobjectiveHillClimbingDistance.getTrace()
getTrace - get the trace of the generator.
the trace of the generator
State metaheuristics.generators.MultiobjectiveHillClimbingDistance.solutionMoreDistance(List< State > state, List< Double > distanceSolution)
solutionMoreDistance - find the solution with the maximum distance.
state the list of states distanceSolution the list of distances corresponding to the states the state with the maximum distance
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference.
boolean metaheuristics.generators.MultiobjectiveHillClimbingDistance.contain(State state)
contain - check if the state is contained in the visited states.
state return true if the state is contained, false otherwise
References problem.definition.State.Comparator, metaheuristics.generators.MultiobjectiveHillClimbingDistance.visitedState.
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference.