metaheuristics::generators::Generator
int metaheuristics.generators.Generator.countGender
Referenced by metaheurictics.strategy.Strategy.updateCountGender.
int metaheuristics.generators.Generator.countBetterGender
Referenced by metaheurictics.strategy.Strategy.updateCountGender.
abstract State metaheuristics.generators.Generator.generate(Integer operatornumber)
Referenced by metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.MultiGenerator.generate.
abstract void metaheuristics.generators.Generator.updateReference(State stateCandidate, Integer countIterationsCurrent)
abstract State metaheuristics.generators.Generator.getReference()
abstract void metaheuristics.generators.Generator.setInitialReference(State stateInitialRef)
abstract GeneratorType metaheuristics.generators.Generator.getType()
Referenced by metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, local_search.acceptation_type.Dominance.listDominance, metaheuristics.generators.InstanceDE.run, metaheuristics.generators.InstanceEE.run, metaheuristics.generators.InstanceGA.run, metaheurictics.strategy.Strategy.updateCountGender, metaheurictics.strategy.Strategy.updateWeight.
abstract List< State > metaheuristics.generators.Generator.getReferenceList()
abstract List< State > metaheuristics.generators.Generator.getSonList()
abstract boolean metaheuristics.generators.Generator.awardUpdateREF(State stateCandidate)
abstract void metaheuristics.generators.Generator.setWeight(float weight)
Referenced by metaheurictics.strategy.Strategy.updateWeight.
abstract float metaheuristics.generators.Generator.getWeight()
abstract float[] metaheuristics.generators.Generator.getTrace()
abstract int[] metaheuristics.generators.Generator.getListCountBetterGender()
Referenced by metaheurictics.strategy.Strategy.updateCountGender.
abstract int[] metaheuristics.generators.Generator.getListCountGender()
Referenced by metaheurictics.strategy.Strategy.updateCountGender.