problem::definition::Operator
abstract List< State > problem.definition.Operator.generatedNewState(State stateCurrent, Integer operatornumber)
Generar nuevos estados a partir de un estado dado.
stateCurrent estado base operatornumber índice de operador (uso dependiente de la implementación) lista de estados generados
Referenced by metaheuristics.generators.HillClimbing.generate, metaheuristics.generators.HillClimbingRestart.generate, metaheuristics.generators.LimitThreshold.generate, metaheuristics.generators.MultiCaseSimulatedAnnealing.generate, metaheuristics.generators.MultiobjectiveHillClimbingDistance.generate, metaheuristics.generators.MultiobjectiveHillClimbingRestart.generate, metaheuristics.generators.MultiobjectiveStochasticHillClimbing.generate, metaheuristics.generators.MultiobjectiveTabuSearch.generate, metaheuristics.generators.SimulatedAnnealing.generate, metaheuristics.generators.TabuSearch.generate, local_search.candidate_type.CandidateValue.stateCandidate, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
abstract List< State > problem.definition.Operator.generateRandomState(Integer operatornumber)
Generar un conjunto de estados aleatorios.
operatornumber índice/semilla opcional para la generación lista de estados aleatorios
Referenced by metaheuristics.generators.HillClimbingRestart.generate, metaheuristics.generators.RandomSearch.generate, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.