metaheurictics::strategy::Strategy
Strategy metaheurictics.strategy.Strategy.strategy
Referenced by metaheurictics.strategy.Strategy.destroyExecute, metaheurictics.strategy.Strategy.getStrategy.
State metaheurictics.strategy.Strategy.bestState
Referenced by metaheurictics.strategy.Strategy.executeStrategy, metaheurictics.strategy.Strategy.getBestState, metaheurictics.strategy.Strategy.updateRef.
Problem metaheurictics.strategy.Strategy.problem
Referenced by metaheurictics.strategy.Strategy.executeStrategy, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.setProblem.
StopExecute metaheurictics.strategy.Strategy.stopexecute
Referenced by metaheurictics.strategy.Strategy.executeStrategy, metaheurictics.strategy.Strategy.getStopexecute, metaheurictics.strategy.Strategy.setStopexecute.
UpdateParameter metaheurictics.strategy.Strategy.updateparameter
Referenced by metaheurictics.strategy.Strategy.getUpdateparameter, metaheurictics.strategy.Strategy.setUpdateparameter.
IFFactoryGenerator metaheurictics.strategy.Strategy.ifFactoryGenerator
Referenced by metaheurictics.strategy.Strategy.newGenerator, metaheurictics.strategy.Strategy.update.
int metaheurictics.strategy.Strategy.countCurrent
Referenced by metaheurictics.strategy.Strategy.executeStrategy, metaheurictics.strategy.Strategy.getCountCurrent, metaheurictics.strategy.Strategy.setCountCurrent.
int metaheurictics.strategy.Strategy.countMax
Referenced by metaheurictics.strategy.Strategy.getCountMax, metaheurictics.strategy.Strategy.setCountMax.
int metaheurictics.strategy.Strategy.countPeriodo
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
int metaheurictics.strategy.Strategy.periodo
Referenced by metaheurictics.strategy.Strategy.executeStrategy, metaheurictics.strategy.Strategy.updateCountGender.
SortedMap<GeneratorType, Generator> metaheurictics.strategy.Strategy.mapGenerators
Referenced by metaheurictics.strategy.Strategy.getListKey, metaheuristics.generators.DistributionEstimationAlgorithm.getListStateRef, metaheuristics.generators.EvolutionStrategies.getListStateRef, metaheuristics.generators.GeneticAlgorithm.getListStateRef, metaheuristics.generators.ParticleSwarmOptimization.getListStateRef, metaheurictics.strategy.Strategy.initialize, metaheurictics.strategy.Strategy.initializeGenerators.
Generator metaheurictics.strategy.Strategy.generator
Referenced by metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.MultiGenerator.generate, metaheurictics.strategy.Strategy.initialize, metaheurictics.strategy.Strategy.initializeGenerators, local_search.acceptation_type.Dominance.listDominance, metaheurictics.strategy.Strategy.newGenerator, local_search.complement.UpdateParameter.updateParameter, metaheurictics.strategy.Strategy.updateRef, metaheurictics.strategy.Strategy.updateRefGenerator.
double metaheurictics.strategy.Strategy.threshold
Referenced by metaheurictics.strategy.Strategy.getThreshold, metaheurictics.strategy.Strategy.setThreshold.
List<State> metaheurictics.strategy.Strategy.listStates
Referenced by metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.MultiGenerator.initializeGenerators.
List<State> metaheurictics.strategy.Strategy.listBest
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
List<State> metaheurictics.strategy.Strategy.listRefPoblacFinal
Referenced by local_search.acceptation_type.AcceptMulticase.acceptCandidate, local_search.acceptation_type.AcceptNotDominated.acceptCandidate, local_search.acceptation_type.AcceptNotDominatedTabu.acceptCandidate, metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
Dominance metaheurictics.strategy.Strategy.notDominated
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
boolean metaheurictics.strategy.Strategy.saveListStates
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
boolean metaheurictics.strategy.Strategy.saveListBestStates
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
boolean metaheurictics.strategy.Strategy.saveFreneParetoMonoObjetivo
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
boolean metaheurictics.strategy.Strategy.calculateTime
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
float [] metaheurictics.strategy.Strategy.listOfflineError
Referenced by metaheurictics.strategy.Strategy.calculateOffLinePerformance.
int metaheurictics.strategy.Strategy.countPeriodChange
Referenced by metaheurictics.strategy.Strategy.calculateOffLinePerformance, metaheurictics.strategy.Strategy.executeStrategy.
int metaheurictics.strategy.Strategy.countChange
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
long metaheurictics.strategy.Strategy.initialTime
long metaheurictics.strategy.Strategy.finalTime
long metaheurictics.strategy.Strategy.timeExecute
metaheurictics.strategy.Strategy.Strategy()
Strategy - method constructor of Strategy singleton.
Referenced by metaheurictics.strategy.Strategy.getStrategy, metaheurictics.strategy.Strategy.update.
static Strategy metaheurictics.strategy.Strategy.getStrategy()
getStrategy - getter of Strategy singleton instance
Strategy instance
References metaheurictics.strategy.Strategy.Strategy, metaheurictics.strategy.Strategy.strategy.
Referenced by local_search.acceptation_type.AcceptBest.acceptCandidate, local_search.acceptation_type.AcceptMulticase.acceptCandidate, local_search.acceptation_type.AcceptNotBad.acceptCandidate, local_search.acceptation_type.AcceptNotBadT.acceptCandidate, local_search.acceptation_type.AcceptNotBadU.acceptCandidate, local_search.acceptation_type.AcceptNotDominated.acceptCandidate, local_search.acceptation_type.AcceptNotDominatedTabu.acceptCandidate, metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, evolutionary_algorithms.complement.OnePointCrossover.crossover, local_search.acceptation_type.Dominance.dominance, problem.extension.FactoresPonderados.evaluationState, problem.extension.MultiObjetivoPuro.evaluationState, evolutionary_algorithms.complement.AIOMutation.fillPath, metaheuristics.generators.ParticleSwarmOptimization.gBestInicial, metaheuristics.generators.DistributionEstimationAlgorithm.generate, metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.GeneticAlgorithm.generate, metaheuristics.generators.HillClimbing.generate, metaheuristics.generators.HillClimbingRestart.generate, metaheuristics.generators.LimitThreshold.generate, metaheuristics.generators.MultiCaseSimulatedAnnealing.generate, metaheuristics.generators.MultiGenerator.generate, metaheuristics.generators.MultiobjectiveHillClimbingDistance.generate, metaheuristics.generators.MultiobjectiveHillClimbingRestart.generate, metaheuristics.generators.MultiobjectiveStochasticHillClimbing.generate, metaheuristics.generators.MultiobjectiveTabuSearch.generate, metaheuristics.generators.RandomSearch.generate, metaheuristics.generators.SimulatedAnnealing.generate, metaheuristics.generators.TabuSearch.generate, problem_operators.MutationOperator.generatedNewState, metaheuristics.generators.DistributionEstimationAlgorithm.getListStateRef, metaheuristics.generators.EvolutionStrategies.getListStateRef, metaheuristics.generators.GeneticAlgorithm.getListStateRef, metaheuristics.generators.ParticleSwarmOptimization.getListStateRef, metaheuristics.generators.DistributionEstimationAlgorithm.getReference, metaheuristics.generators.EvolutionStrategies.getReference, metaheuristics.generators.GeneticAlgorithm.getReference, metaheuristics.generators.HillClimbing.HillClimbing, metaheuristics.generators.HillClimbingRestart.HillClimbingRestart, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, metaheuristics.generators.MultiGenerator.initializeGenerators, metaheuristics.generators.LimitThreshold.LimitThreshold, local_search.acceptation_type.Dominance.listDominance, evolutionary_algorithms.complement.ProbabilisticSampling.listState, evolutionary_algorithms.complement.AIOMutation.mutation, evolutionary_algorithms.complement.OnePointMutation.mutation, evolutionary_algorithms.complement.TowPointsMutation.mutation, evolutionary_algorithms.complement.SteadyStateReplace.replace, evolutionary_algorithms.complement.ProbabilisticSampling.sampling, metaheuristics.generators.MultiGenerator.searchState, evolutionary_algorithms.complement.TruncationSelection.selection, local_search.candidate_type.CandidateValue.stateCandidate, local_search.candidate_type.NotDominatedCandidate.stateSearch, metaheuristics.generators.TabuSearch.TabuSearch, metaheuristics.generators.MultiGenerator.updateAwardImp, metaheuristics.generators.MultiGenerator.updateAwardSC, local_search.complement.UpdateParameter.updateParameter, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference, metaheuristics.generators.Particle.updateReference, metaheuristics.generators.ParticleSwarmOptimization.updateReference, metaheuristics.generators.Particle.UpdateVelocity.
static void metaheurictics.strategy.Strategy.destroyExecute()
References metaheuristics.generators.RandomSearch.listStateReference, metaheurictics.strategy.Strategy.strategy.
void metaheurictics.strategy.Strategy.executeStrategy(int countmaxIterations, int countIterationsChange, int operatornumber, GeneratorType generatorType)
executeStrategy - method to execute the strategy.
countmaxIterations countIterationsChange operatornumber generatorType
References metaheurictics.strategy.Strategy.bestState, metaheurictics.strategy.Strategy.calculateOffLinePerformance, metaheurictics.strategy.Strategy.calculateTime, metaheurictics.strategy.Strategy.countChange, metaheurictics.strategy.Strategy.countCurrent, metaheurictics.strategy.Strategy.countPeriodChange, metaheurictics.strategy.Strategy.countPeriodo, metaheuristics.generators.Generator.generate, metaheuristics.generators.MultiGenerator.generate, metaheurictics.strategy.Strategy.generator, problem.definition.State.getEvaluation, metaheurictics.strategy.Strategy.getProblem, metaheuristics.generators.MultiGenerator.getReferenceList, metaheurictics.strategy.Strategy.initialize, metaheurictics.strategy.Strategy.initializeGenerators, metaheuristics.generators.MultiGenerator.initializeGenerators, metaheurictics.strategy.Strategy.listBest, metaheuristics.generators.MultiGenerator.listGeneratedPP, metaheurictics.strategy.Strategy.listRefPoblacFinal, metaheurictics.strategy.Strategy.listStates, problem.definition.Problem.ProblemType.Maximizar, problem.definition.Problem.ProblemType.Minimizar, metaheuristics.generators.GeneratorType.MultiGenerator, metaheurictics.strategy.Strategy.newGenerator, metaheurictics.strategy.Strategy.notDominated, metaheurictics.strategy.Strategy.periodo, metaheurictics.strategy.Strategy.problem, metaheurictics.strategy.Strategy.saveFreneParetoMonoObjetivo, metaheurictics.strategy.Strategy.saveListBestStates, metaheurictics.strategy.Strategy.saveListStates, problem.definition.State.setEvaluation, problem.definition.State.setNumber, problem.definition.Problem.setState, problem.definition.State.setTypeGenerator, metaheurictics.strategy.Strategy.stopexecute, metaheurictics.strategy.Strategy.update, metaheurictics.strategy.Strategy.updateCountGender, local_search.complement.UpdateParameter.updateParameter, metaheurictics.strategy.Strategy.updateRef, metaheuristics.generators.MultiGenerator.updateReference, metaheurictics.strategy.Strategy.updateWeight.
void metaheurictics.strategy.Strategy.updateCountGender()
References metaheuristics.generators.Generator.countBetterGender, metaheuristics.generators.Generator.countGender, metaheuristics.generators.Generator.getListCountBetterGender, metaheuristics.generators.Generator.getListCountGender, metaheuristics.generators.MultiGenerator.getListGenerators, metaheuristics.generators.Generator.getType, metaheuristics.generators.GeneratorType.MultiGenerator, metaheurictics.strategy.Strategy.periodo.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
void metaheurictics.strategy.Strategy.updateWeight()
updateWeight - method to update the weight of the generators.
References metaheuristics.generators.MultiGenerator.getListGenerators, metaheuristics.generators.Generator.getType, metaheuristics.generators.GeneratorType.MultiGenerator, metaheuristics.generators.Generator.setWeight.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
void metaheurictics.strategy.Strategy.update(Integer countIterationsCurrent)
References metaheuristics.generators.DistributionEstimationAlgorithm.countRef, metaheuristics.generators.EvolutionStrategies.countRef, metaheuristics.generators.GeneticAlgorithm.countRef, metaheuristics.generators.GeneratorType.DistributionEstimationAlgorithm, metaheuristics.generators.GeneratorType.EvolutionStrategies, metaheuristics.generators.GeneratorType.GeneticAlgorithm, metaheuristics.generators.ParticleSwarmOptimization.getCountRef, metaheurictics.strategy.Strategy.ifFactoryGenerator, metaheuristics.generators.GeneratorType.ParticleSwarmOptimization, metaheurictics.strategy.Strategy.Strategy.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
Generator metaheurictics.strategy.Strategy.newGenerator(GeneratorType Generatortype)
newGenerator - method to create a new generator.
Generatortype return a Generator
References metaheurictics.strategy.Strategy.generator, metaheurictics.strategy.Strategy.ifFactoryGenerator.
Referenced by metaheurictics.strategy.Strategy.executeStrategy, metaheurictics.strategy.Strategy.initialize, metaheurictics.strategy.Strategy.initializeGenerators.
State metaheurictics.strategy.Strategy.getBestState()
getBestState - method to get the best state.
return the best state
References metaheurictics.strategy.Strategy.bestState.
Referenced by metaheuristics.generators.MultiGenerator.searchState.
void metaheurictics.strategy.Strategy.setBestState(State besState)
setBestState - method to set the best state.
besState
StopExecute metaheurictics.strategy.Strategy.getStopexecute()
getStopexecute - method to get the stop execute.
return the stop execute
References metaheurictics.strategy.Strategy.stopexecute.
int metaheurictics.strategy.Strategy.getCountMax()
getCountMax - method to get the maximum count.
return the maximum count
References metaheurictics.strategy.Strategy.countMax.
void metaheurictics.strategy.Strategy.setCountMax(int countMax)
setCountMax - method to set the maximum count.
countMax
References metaheurictics.strategy.Strategy.countMax.
void metaheurictics.strategy.Strategy.setStopexecute(StopExecute stopexecute)
setStopexecute - method to set the stop execute.
stopexecute
References metaheurictics.strategy.Strategy.stopexecute.
UpdateParameter metaheurictics.strategy.Strategy.getUpdateparameter()
getUpdateparameter - method to get the update parameter.
return the update parameter
References metaheurictics.strategy.Strategy.updateparameter.
void metaheurictics.strategy.Strategy.setUpdateparameter(UpdateParameter updateparameter)
setUpdateparameter - method to set the update parameter.
updateparameter
References metaheurictics.strategy.Strategy.updateparameter.
Problem metaheurictics.strategy.Strategy.getProblem()
getProblem - method to get the problem.
return the problem
References metaheurictics.strategy.Strategy.problem.
Referenced by local_search.acceptation_type.AcceptBest.acceptCandidate, local_search.acceptation_type.AcceptNotBad.acceptCandidate, local_search.acceptation_type.AcceptNotBadT.acceptCandidate, local_search.acceptation_type.AcceptNotBadU.acceptCandidate, metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, evolutionary_algorithms.complement.OnePointCrossover.crossover, local_search.acceptation_type.Dominance.dominance, problem.extension.FactoresPonderados.evaluationState, problem.extension.MultiObjetivoPuro.evaluationState, metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.ParticleSwarmOptimization.gBestInicial, metaheuristics.generators.DistributionEstimationAlgorithm.generate, metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.GeneticAlgorithm.generate, metaheuristics.generators.HillClimbing.generate, metaheuristics.generators.HillClimbingRestart.generate, metaheuristics.generators.LimitThreshold.generate, metaheuristics.generators.MultiCaseSimulatedAnnealing.generate, metaheuristics.generators.MultiobjectiveHillClimbingDistance.generate, metaheuristics.generators.MultiobjectiveHillClimbingRestart.generate, metaheuristics.generators.MultiobjectiveStochasticHillClimbing.generate, metaheuristics.generators.MultiobjectiveTabuSearch.generate, metaheuristics.generators.RandomSearch.generate, metaheuristics.generators.SimulatedAnnealing.generate, metaheuristics.generators.TabuSearch.generate, problem_operators.MutationOperator.generatedNewState, metaheuristics.generators.DistributionEstimationAlgorithm.getReference, metaheuristics.generators.EvolutionStrategies.getReference, metaheuristics.generators.GeneticAlgorithm.getReference, metaheuristics.generators.HillClimbing.HillClimbing, metaheuristics.generators.HillClimbingRestart.HillClimbingRestart, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, metaheuristics.generators.MultiGenerator.initializeGenerators, metaheuristics.generators.LimitThreshold.LimitThreshold, evolutionary_algorithms.complement.AIOMutation.mutation, evolutionary_algorithms.complement.OnePointMutation.mutation, evolutionary_algorithms.complement.TowPointsMutation.mutation, evolutionary_algorithms.complement.SteadyStateReplace.replace, evolutionary_algorithms.complement.ProbabilisticSampling.sampling, metaheuristics.generators.MultiGenerator.searchState, evolutionary_algorithms.complement.TruncationSelection.selection, local_search.candidate_type.CandidateValue.stateCandidate, local_search.candidate_type.NotDominatedCandidate.stateSearch, metaheuristics.generators.TabuSearch.TabuSearch, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference, metaheuristics.generators.Particle.updateReference, metaheuristics.generators.ParticleSwarmOptimization.updateReference, metaheurictics.strategy.Strategy.updateRefGenerator.
void metaheurictics.strategy.Strategy.setProblem(Problem problem)
setProblem - method to set the problem.
problem
References metaheurictics.strategy.Strategy.problem.
ArrayList< String > metaheurictics.strategy.Strategy.getListKey()
getListKey - method to get the list of keys.
return the list of keys
References metaheurictics.strategy.Strategy.mapGenerators.
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getListStateRef, metaheuristics.generators.EvolutionStrategies.getListStateRef, metaheuristics.generators.GeneticAlgorithm.getListStateRef, metaheuristics.generators.ParticleSwarmOptimization.getListStateRef.
void metaheurictics.strategy.Strategy.initializeGenerators()
initializeGenerators - method to initialize the generators.
References metaheurictics.strategy.Strategy.generator, metaheurictics.strategy.Strategy.mapGenerators, metaheurictics.strategy.Strategy.newGenerator.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
void metaheurictics.strategy.Strategy.initialize()
initialize - method to initialize the generators.
References metaheurictics.strategy.Strategy.generator, metaheurictics.strategy.Strategy.mapGenerators, metaheurictics.strategy.Strategy.newGenerator.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
int metaheurictics.strategy.Strategy.getCountCurrent()
getCountCurrent - method to get the current count.
return the current count
References metaheurictics.strategy.Strategy.countCurrent.
Referenced by metaheuristics.generators.HillClimbingRestart.generate, evolutionary_algorithms.complement.ProbabilisticSampling.listState, metaheuristics.generators.MultiGenerator.updateAwardImp, metaheuristics.generators.MultiGenerator.updateAwardSC.
void metaheurictics.strategy.Strategy.setCountCurrent(int countCurrent)
setCountCurrent - method to set the current count.
countCurrent
References metaheurictics.strategy.Strategy.countCurrent.
double metaheurictics.strategy.Strategy.getThreshold()
getThreshold - method to get the threshold.
return the threshold
References metaheurictics.strategy.Strategy.threshold.
Referenced by local_search.acceptation_type.AcceptNotBadU.acceptCandidate.
void metaheurictics.strategy.Strategy.setThreshold(double threshold)
setThreshold - method to set the threshold.
threshold
References metaheurictics.strategy.Strategy.threshold.
void metaheurictics.strategy.Strategy.calculateOffLinePerformance(float sumMax, int countOff)
calculateOffLinePerformance - method to calculate the offline performance.
sumMax countOff
References metaheurictics.strategy.Strategy.countPeriodChange, metaheurictics.strategy.Strategy.listOfflineError.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
void metaheurictics.strategy.Strategy.updateRef(GeneratorType generatorType)
updateRef - method to update the reference.
generatorType
References metaheurictics.strategy.Strategy.bestState, metaheurictics.strategy.Strategy.generator, metaheuristics.generators.MultiGenerator.listStateReference, metaheuristics.generators.GeneratorType.MultiGenerator, metaheurictics.strategy.Strategy.updateRefGenerator, metaheurictics.strategy.Strategy.updateRefMultiG.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
void metaheurictics.strategy.Strategy.updateRefMultiG()
updateRefMultiG - method to update the reference for multi-generators.
References metaheuristics.generators.MultiGenerator.getListGenerators, metaheurictics.strategy.Strategy.updateRefGenerator.
Referenced by metaheurictics.strategy.Strategy.updateRef.
void metaheurictics.strategy.Strategy.updateRefGenerator(Generator generator)
updateRefGenerator - method to update the reference for generators.
generator
References metaheuristics.generators.GeneratorType.DistributionEstimationAlgorithm, metaheuristics.generators.GeneratorType.EvolutionStrategies, metaheurictics.strategy.Strategy.generator, metaheuristics.generators.GeneratorType.GeneticAlgorithm, problem.definition.Problem.getFunction, metaheurictics.strategy.Strategy.getProblem, metaheuristics.generators.GeneratorType.HillClimbing, metaheuristics.generators.GeneratorType.RandomSearch, metaheuristics.generators.GeneratorType.SimulatedAnnealing, metaheuristics.generators.GeneratorType.TabuSearch.
Referenced by metaheurictics.strategy.Strategy.updateRef, metaheurictics.strategy.Strategy.updateRefMultiG.