evolutionary_algorithms::complement::Probability
Object evolutionary_algorithms.complement.Probability.key
Referenced by evolutionary_algorithms.complement.Probability.getKey, evolutionary_algorithms.complement.Probability.setKey.
Object evolutionary_algorithms.complement.Probability.value
Referenced by evolutionary_algorithms.complement.Probability.getValue, evolutionary_algorithms.complement.Probability.setValue.
float evolutionary_algorithms.complement.Probability.probability
Referenced by evolutionary_algorithms.complement.Probability.getProbability, evolutionary_algorithms.complement.Probability.setProbability.
float evolutionary_algorithms.complement.Probability.getProbability()
getProbability - getter for the probability.
returns the probability
References evolutionary_algorithms.complement.Probability.probability.
void evolutionary_algorithms.complement.Probability.setProbability(float probability)
setProbability - setter for the probability.
probability
References evolutionary_algorithms.complement.Probability.probability.
Referenced by evolutionary_algorithms.complement.Univariate.distribution.
Object evolutionary_algorithms.complement.Probability.getKey()
getKey - getter for the key.
returns the key
References evolutionary_algorithms.complement.Probability.key.
void evolutionary_algorithms.complement.Probability.setKey(Object key)
setKey - setter for the key.
key
References evolutionary_algorithms.complement.Probability.key.
Referenced by evolutionary_algorithms.complement.Univariate.distribution.
Object evolutionary_algorithms.complement.Probability.getValue()
getValue - getter for the value.
returns the value
References evolutionary_algorithms.complement.Probability.value.
void evolutionary_algorithms.complement.Probability.setValue(Object value)
setValue - setter for the value.
value
References evolutionary_algorithms.complement.Probability.value.
Referenced by evolutionary_algorithms.complement.Univariate.distribution.