local_search::acceptation_type::AcceptableCandidate
abstract Boolean local_search.acceptation_type.AcceptableCandidate.acceptCandidate(State stateCurrent, State stateCandidate)
Evaluate whether a candidate state should be accepted.
stateCurrent the current state stateCandidate the candidate state true if the candidate should be accepted, false otherwise IllegalArgumentException on invalid arguments SecurityException on reflective access problems ClassNotFoundException when a referenced class cannot be found InstantiationException on reflective instantiation failures IllegalAccessException on illegal reflective access InvocationTargetException when a reflective call throws NoSuchMethodException when a reflective method lookup fails
Referenced by metaheuristics.generators.HillClimbing.updateReference, metaheuristics.generators.HillClimbingRestart.updateReference, metaheuristics.generators.LimitThreshold.updateReference, metaheuristics.generators.MultiCaseSimulatedAnnealing.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference, metaheuristics.generators.MultiobjectiveStochasticHillClimbing.updateReference, metaheuristics.generators.MultiobjectiveTabuSearch.updateReference, metaheuristics.generators.RandomSearch.updateReference, metaheuristics.generators.SimulatedAnnealing.updateReference, metaheuristics.generators.TabuSearch.updateReference.