problem::definition::Problem
ArrayList<ObjetiveFunction> problem.definition.Problem.function
State problem.definition.Problem.state
Referenced by problem.definition.Problem.Evaluate, problem.definition.Problem.getState, problem.definition.Problem.setState.
ProblemType problem.definition.Problem.typeProblem
Referenced by problem.definition.Problem.getTypeProblem, problem.definition.Problem.setTypeProblem.
Codification problem.definition.Problem.codification
Referenced by problem.definition.Problem.getCodification, problem.definition.Problem.setCodification.
Operator problem.definition.Problem.operator
Referenced by problem.definition.Problem.getOperator, problem.definition.Problem.setOperator.
int problem.definition.Problem.possibleValue
Referenced by problem.definition.Problem.getPossibleValue, problem.definition.Problem.setPossibleValue.
TypeSolutionMethod problem.definition.Problem.typeSolutionMethod
Referenced by problem.definition.Problem.Evaluate, problem.definition.Problem.getTypeSolutionMethod, problem.definition.Problem.newSolutionMethod, problem.definition.Problem.setTypeSolutionMethod.
IFFactorySolutionMethod problem.definition.Problem.factorySolutionMethod
Referenced by problem.definition.Problem.getFactorySolutionMethod, problem.definition.Problem.newSolutionMethod, problem.definition.Problem.setFactorySolutionMethod.
problem.definition.Problem.Problem()
Constructor por defecto.
Inicializa una instancia vacía; los componentes concretos (funciones, codificación, operador) se deben inyectar mediante los setters antes de usar Evaluate(State).
ArrayList< ObjetiveFunction > problem.definition.Problem.getFunction()
Obtener la lista de funciones objetivo del problema.
copia defensiva de la lista de ObjetiveFunction; nunca devuelve la referencia interna (puede ser lista vacía).
Referenced by problem.extension.FactoresPonderados.evaluationState, problem.extension.MultiObjetivoPuro.evaluationState, metaheuristics.generators.DistributionEstimationAlgorithm.generate, metaheurictics.strategy.Strategy.updateRefGenerator.
void problem.definition.Problem.setFunction(ArrayList< ObjetiveFunction > function)
Establecer las funciones objetivo del problema.
Se realiza una copia defensiva de la lista proporcionada. function lista de funciones objetivo
State problem.definition.Problem.getState()
Obtener una copia del estado actual del problema.
Devuelve una copia para evitar aliasing con la representación interna. copia de State o null si no hay estado inicial.
References problem.definition.Problem.state.
Referenced by metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.GeneticAlgorithm.generate, metaheuristics.generators.MultiGenerator.initializeGenerators.
void problem.definition.Problem.setState(State state)
Establecer el estado actual del problema (copia defensiva).
state estado a asignar; si es null se resetea el estado interno.
References problem.definition.Problem.state.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
ProblemType problem.definition.Problem.getTypeProblem()
Obtener el tipo de problema (Maximizar / Minimizar).
el ProblemType configurado para este problema
References problem.definition.Problem.typeProblem.
Referenced by local_search.acceptation_type.Dominance.dominance, problem.extension.FactoresPonderados.evaluationState, problem.extension.MultiObjetivoPuro.evaluationState, metaheuristics.generators.ParticleSwarmOptimization.gBestInicial, metaheuristics.generators.DistributionEstimationAlgorithm.getReference, metaheuristics.generators.EvolutionStrategies.getReference, metaheuristics.generators.GeneticAlgorithm.getReference, metaheuristics.generators.HillClimbing.HillClimbing, metaheuristics.generators.HillClimbingRestart.HillClimbingRestart, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, evolutionary_algorithms.complement.SteadyStateReplace.replace, metaheuristics.generators.MultiGenerator.searchState, evolutionary_algorithms.complement.TruncationSelection.selection, metaheuristics.generators.Particle.updateReference, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
void problem.definition.Problem.setTypeProblem(ProblemType typeProblem)
Establecer el tipo de problema.
typeProblem tipo de problema (Maximizar o Minimizar)
References problem.definition.Problem.typeProblem.
Codification problem.definition.Problem.getCodification()
Obtener la codificación usada para representar estados.
la Codification configurada
References problem.definition.Problem.codification.
Referenced by evolutionary_algorithms.complement.OnePointCrossover.crossover, problem_operators.MutationOperator.generatedNewState, evolutionary_algorithms.complement.AIOMutation.mutation, evolutionary_algorithms.complement.OnePointMutation.mutation, evolutionary_algorithms.complement.TowPointsMutation.mutation, evolutionary_algorithms.complement.ProbabilisticSampling.sampling.
void problem.definition.Problem.setCodification(Codification codification)
Establecer la codificación de variables para el problema.
codification implementación de Codification
References problem.definition.Problem.codification.
Operator problem.definition.Problem.getOperator()
Obtener el operador encargado de generar nuevos estados.
operador configurado
References problem.definition.Problem.operator.
Referenced by metaheuristics.generators.HillClimbing.generate, metaheuristics.generators.HillClimbingRestart.generate, metaheuristics.generators.LimitThreshold.generate, metaheuristics.generators.MultiCaseSimulatedAnnealing.generate, metaheuristics.generators.MultiobjectiveHillClimbingDistance.generate, metaheuristics.generators.MultiobjectiveHillClimbingRestart.generate, metaheuristics.generators.MultiobjectiveStochasticHillClimbing.generate, metaheuristics.generators.MultiobjectiveTabuSearch.generate, metaheuristics.generators.RandomSearch.generate, metaheuristics.generators.SimulatedAnnealing.generate, metaheuristics.generators.TabuSearch.generate, local_search.candidate_type.CandidateValue.stateCandidate, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
void problem.definition.Problem.setOperator(Operator operator)
Establecer el operador de generación de estados.
operator operador que implementa la generación de estados
References problem.definition.Problem.operator.
int problem.definition.Problem.getPossibleValue()
Obtener el número de valores posibles (uso dependiente de la codificación).
número de valores posibles
References problem.definition.Problem.possibleValue.
Referenced by evolutionary_algorithms.complement.ProbabilisticSampling.sampling.
void problem.definition.Problem.setPossibleValue(int possibleValue)
Establecer el número de valores posibles.
possibleValue número de valores
References problem.definition.Problem.possibleValue.
void problem.definition.Problem.Evaluate(State state)
Evaluar un estado de solución.
Dependiendo del typeSolutionMethod realiza una evaluación simple usando la primera función objetivo o delega en un SolutionMethod. state estado a evaluar (se modifica su lista de evaluaciones) ReflectiveOperationException si falla la creación reflexiva del método de solución
References problem.extension.SolutionMethod.evaluationState, problem.definition.Problem.newSolutionMethod, problem.definition.Problem.state, problem.definition.Problem.typeSolutionMethod.
Referenced by metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, metaheuristics.generators.HillClimbingRestart.generate, local_search.candidate_type.NotDominatedCandidate.stateSearch, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
TypeSolutionMethod problem.definition.Problem.getTypeSolutionMethod()
Obtener el tipo de método de solución configurado.
tipo de método de solución o null
References problem.definition.Problem.typeSolutionMethod.
void problem.definition.Problem.setTypeSolutionMethod(TypeSolutionMethod typeSolutionMethod)
Establecer el tipo de método de solución.
typeSolutionMethod tipo a usar para evaluar estados
References problem.definition.Problem.typeSolutionMethod.
IFFactorySolutionMethod problem.definition.Problem.getFactorySolutionMethod()
Obtener la fábrica de métodos de solución.
fábrica configurada (puede ser null)
References problem.definition.Problem.factorySolutionMethod.
void problem.definition.Problem.setFactorySolutionMethod(IFFactorySolutionMethod factorySolutionMethod)
References problem.definition.Problem.factorySolutionMethod.
SolutionMethod problem.definition.Problem.newSolutionMethod(TypeSolutionMethod typeSolutionMethod)
Crear una instancia de SolutionMethod para el tipo solicitado.
typeSolutionMethod tipo de método de solución a crear instancia de SolutionMethod ReflectiveOperationException si la creación vía fábrica falla
References problem.definition.Problem.factorySolutionMethod, problem.definition.Problem.typeSolutionMethod.
Referenced by problem.definition.Problem.Evaluate.