problem::definition::State
GeneratorType problem.definition.State.typeGenerator
Referenced by problem.definition.State.getTypeGenerator, problem.definition.State.setTypeGenerator, problem.definition.State.State.
ArrayList<Double> problem.definition.State.evaluation
Referenced by problem.definition.State.getEvaluation, problem.definition.State.setEvaluation.
int problem.definition.State.number
Referenced by problem.definition.State.getNumber, problem.definition.State.setNumber, problem.definition.State.State.
ArrayList<Object> problem.definition.State.code
Referenced by problem.definition.State.getCode, problem.definition.State.State, problem.definition.State.State.
problem.definition.State.State(State ps)
Constructor copia.
Realiza copias defensivas de las colecciones internas. ps estado a copiar (puede ser null)
References problem.definition.State.getCode, problem.definition.State.getEvaluation, problem.definition.State.getNumber, problem.definition.State.getTypeGenerator, problem.definition.State.number, problem.definition.State.State, problem.definition.State.typeGenerator.
Referenced by problem.definition.State.clone, problem.definition.State.Comparator, problem.definition.State.Distance, problem.definition.State.State.
problem.definition.State.State(ArrayList< Object > code)
Construir un estado a partir de la representación de código.
code lista de objetos que representan la codificación interna
References problem.definition.State.code.
problem.definition.State.State()
Constructor por defecto: crea un estado con código vacío.
References problem.definition.State.code.
Referenced by problem.definition.State.clone, problem.definition.State.getCopy.
ArrayList< Object > problem.definition.State.getCode()
Obtener la codificación del estado (copia defensiva).
lista con los elementos de código
References problem.definition.State.code.
Referenced by problem.definition.State.Comparator, evolutionary_algorithms.complement.OnePointCrossover.crossover, evolutionary_algorithms.complement.UniformCrossover.crossover, problem.definition.State.Distance, problem_operators.MutationOperator.generatedNewState, evolutionary_algorithms.complement.AIOMutation.mutation, evolutionary_algorithms.complement.OnePointMutation.mutation, evolutionary_algorithms.complement.TowPointsMutation.mutation, evolutionary_algorithms.complement.AIOMutation.sortedPathValue, problem.definition.State.State.
void problem.definition.State.setCode(ArrayList< Object > listCode)
Establecer la codificación del estado (se copia la lista entrante).
listCode nueva codificación
Referenced by evolutionary_algorithms.complement.OnePointCrossover.crossover, metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.GeneticAlgorithm.generate, metaheuristics.generators.Particle.generate, metaheuristics.generators.ParticleSwarmOptimization.getListStateRef, evolutionary_algorithms.complement.ProbabilisticSampling.listState, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
GeneratorType problem.definition.State.getTypeGenerator()
Obtener el tipo de generador asociado a este estado.
tipo de generador
References problem.definition.State.typeGenerator.
Referenced by problem.definition.State.State.
void problem.definition.State.setTypeGenerator(GeneratorType typeGenerator)
Establecer el tipo de generador responsable de crear este estado.
typeGenerator tipo de generador
References problem.definition.State.typeGenerator.
Referenced by metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.GeneticAlgorithm.generate, evolutionary_algorithms.complement.ProbabilisticSampling.listState, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
ArrayList< Double > problem.definition.State.getEvaluation()
Obtener la lista de evaluaciones del estado.
copia de la lista de evaluaciones (puede ser null)
References problem.definition.State.evaluation.
Referenced by local_search.acceptation_type.AcceptMulticase.acceptCandidate, local_search.acceptation_type.AcceptNotBad.acceptCandidate, problem.extension.MetricasMultiobjetivo.Contains, problem.extension.MetricasMultiobjetivo.Dispersion, problem.extension.MetricasMultiobjetivo.DistanciaGeneracional, local_search.acceptation_type.Dominance.dominance, metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.ParticleSwarmOptimization.gBestInicial, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, evolutionary_algorithms.complement.SteadyStateReplace.maxValue, metaheuristics.generators.DistributionEstimationAlgorithm.maxValue, evolutionary_algorithms.complement.SteadyStateReplace.minValue, evolutionary_algorithms.complement.SteadyStateReplace.replace, metaheuristics.generators.MultiGenerator.searchState, problem.definition.State.State, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
void problem.definition.State.setEvaluation(ArrayList< Double > evaluation)
Establecer la lista de evaluaciones del estado (copia defensiva).
evaluation lista de doubles que representan la evaluación
References problem.definition.State.evaluation.
Referenced by problem.extension.FactoresPonderados.evaluationState, problem.extension.MultiObjetivoPuro.evaluationState, metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.GeneticAlgorithm.generate, metaheuristics.generators.ParticleSwarmOptimization.getListStateRef, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
int problem.definition.State.getNumber()
Obtener el identificador numérico del estado.
número asignado al estado
References problem.definition.State.number.
Referenced by problem.definition.State.State.
void problem.definition.State.setNumber(int number)
Asignar el identificador numérico al estado.
number nuevo identificador
References problem.definition.State.number.
Referenced by metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.GeneticAlgorithm.generate, evolutionary_algorithms.complement.ProbabilisticSampling.listState.
State problem.definition.State.clone()
clone
Devuelve una copia superficial segura (deep-copy de colecciones mutables) del estado. nueva instancia State con copias de las colecciones
References problem.definition.State.State, problem.definition.State.State.
Referenced by local_search.acceptation_type.AcceptMulticase.acceptCandidate, local_search.acceptation_type.AcceptNotDominated.acceptCandidate, local_search.acceptation_type.AcceptNotDominatedTabu.acceptCandidate, local_search.acceptation_type.Dominance.listDominance, metaheuristics.generators.ParticleSwarmOptimization.setLBest, metaheuristics.generators.ParticleSwarmOptimization.setLBestAt, metaheuristics.generators.MultiobjectiveHillClimbingDistance.updateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
Object problem.definition.State.getCopy()
Obtener una copia por valor del estado (implementado con copy-constructor).
objeto State nuevo
References problem.definition.State.State.
Referenced by evolutionary_algorithms.complement.OnePointCrossover.crossover, evolutionary_algorithms.complement.UniformCrossover.crossover, metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.GeneticAlgorithm.generate, problem_operators.MutationOperator.generatedNewState.
boolean problem.definition.State.Comparator(State state)
Comparar la codificación de dos estados.
state estado con el que comparar true si las listas de código son iguales
References problem.definition.State.getCode, problem.definition.State.State.
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.contain, metaheuristics.generators.MultiobjectiveHillClimbingRestart.contain, local_search.acceptation_type.Dominance.listDominance.
double problem.definition.State.Distance(State state)
Calcular la distancia (cantidad de posiciones diferentes) entre dos códigos.
state otro estado a comparar número de posiciones distintas
References problem.definition.State.getCode, problem.definition.State.State.
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingDistance.distanceCalculateAdd.