problem::definition::Codification
abstract boolean problem.definition.Codification.validState(State state)
abstract Object problem.definition.Codification.getVariableAleatoryValue(int key)
Referenced by problem_operators.MutationOperator.generatedNewState, evolutionary_algorithms.complement.OnePointMutation.mutation, evolutionary_algorithms.complement.TowPointsMutation.mutation.
abstract int problem.definition.Codification.getAleatoryKey()
Referenced by problem_operators.MutationOperator.generatedNewState, evolutionary_algorithms.complement.AIOMutation.mutation, evolutionary_algorithms.complement.OnePointMutation.mutation, evolutionary_algorithms.complement.TowPointsMutation.mutation.
abstract int problem.definition.Codification.getVariableCount()
Referenced by evolutionary_algorithms.complement.OnePointCrossover.crossover, evolutionary_algorithms.complement.ProbabilisticSampling.sampling.