metaheuristics::generators::MultiobjectiveHillClimbingRestart
CandidateValue metaheuristics.generators.MultiobjectiveHillClimbingRestart.candidatevalue
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.generate.
AcceptType metaheuristics.generators.MultiobjectiveHillClimbingRestart.typeAcceptation
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
StrategyType metaheuristics.generators.MultiobjectiveHillClimbingRestart.strategy
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.generate.
CandidateType metaheuristics.generators.MultiobjectiveHillClimbingRestart.typeCandidate
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.generate.
State metaheuristics.generators.MultiobjectiveHillClimbingRestart.stateReferenceHC
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.generate, metaheuristics.generators.MultiobjectiveHillClimbingRestart.getReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.getReferenceList, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
IFFactoryAcceptCandidate metaheuristics.generators.MultiobjectiveHillClimbingRestart.ifacceptCandidate
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
GeneratorType metaheuristics.generators.MultiobjectiveHillClimbingRestart.generatortype
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.getGeneratorType, metaheuristics.generators.MultiobjectiveHillClimbingRestart.setGeneratorType.
List<State> metaheuristics.generators.MultiobjectiveHillClimbingRestart.listStateReference
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.getReferenceList.
float metaheuristics.generators.MultiobjectiveHillClimbingRestart.weight
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.MultiobjectiveHillClimbingRestart, metaheuristics.generators.MultiobjectiveHillClimbingRestart.setWeight.
List<Float> metaheuristics.generators.MultiobjectiveHillClimbingRestart.listTrace
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.MultiobjectiveHillClimbingRestart.
List<State> metaheuristics.generators.MultiobjectiveHillClimbingRestart.visitedState
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.contain, metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
final int metaheuristics.generators.MultiobjectiveHillClimbingRestart.sizeNeighbors
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.getSizeNeighbors.
static int metaheuristics.generators.MultiobjectiveHillClimbingRestart.getSizeNeighbors()
Accessor for sizeNeighbors.
References metaheuristics.generators.MultiobjectiveHillClimbingRestart.sizeNeighbors.
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
metaheuristics.generators.MultiobjectiveHillClimbingRestart.MultiobjectiveHillClimbingRestart()
MultiobjectiveHillClimbingRestart - class that implements the Multiobjective Hill Climbing with Restart metaheuristic.
References local_search.acceptation_type.AcceptType.AcceptNotDominated, metaheuristics.generators.MultiobjectiveHillClimbingRestart.listTrace, metaheuristics.generators.GeneratorType.MultiobjectiveHillClimbingRestart, local_search.complement.StrategyType.NORMAL, local_search.candidate_type.CandidateType.NotDominatedCandidate, metaheuristics.generators.MultiobjectiveHillClimbingRestart.weight.
State metaheuristics.generators.MultiobjectiveHillClimbingRestart.generate(Integer operatornumber)
generate - generate a new state based on the operator number.
operatornumber the operator number to use for generating the state the generated state
References metaheuristics.generators.MultiobjectiveHillClimbingRestart.candidatevalue, problem.definition.Operator.generatedNewState, problem.definition.Problem.getOperator, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.MultiobjectiveHillClimbingRestart.stateReferenceHC, metaheuristics.generators.MultiobjectiveHillClimbingRestart.strategy, metaheuristics.generators.MultiobjectiveHillClimbingRestart.typeCandidate.
void metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference(State stateCandidate, Integer countIterationsCurrent)
updateReference - update the reference state and the list of visited states.
stateCandidate countIterationsCurrent
References local_search.acceptation_type.AcceptableCandidate.acceptCandidate, problem.definition.State.clone, metaheuristics.generators.MultiobjectiveHillClimbingRestart.contain, problem.definition.Problem.Evaluate, problem.definition.Operator.generatedNewState, problem.definition.Operator.generateRandomState, problem.definition.Problem.getOperator, metaheurictics.strategy.Strategy.getProblem, metaheuristics.generators.MultiobjectiveHillClimbingRestart.getReferenceList, metaheuristics.generators.MultiobjectiveHillClimbingRestart.getSizeNeighbors, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.MultiobjectiveHillClimbingRestart.ifacceptCandidate, metaheurictics.strategy.Strategy.listRefPoblacFinal, metaheuristics.generators.MultiobjectiveHillClimbingRestart.stateReferenceHC, metaheuristics.generators.MultiobjectiveHillClimbingRestart.typeAcceptation, metaheuristics.generators.MultiobjectiveHillClimbingRestart.visitedState.
List< State > metaheuristics.generators.MultiobjectiveHillClimbingRestart.getReferenceList()
getReferenceList - get the list of reference states.
the list of reference states
References metaheuristics.generators.MultiobjectiveHillClimbingRestart.listStateReference, metaheuristics.generators.MultiobjectiveHillClimbingRestart.stateReferenceHC.
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.
State metaheuristics.generators.MultiobjectiveHillClimbingRestart.getReference()
getReference - get the reference state.
the reference state
References metaheuristics.generators.MultiobjectiveHillClimbingRestart.stateReferenceHC.
void metaheuristics.generators.MultiobjectiveHillClimbingRestart.setStateRef(State stateRef)
setStateRef - set the reference state.
stateRef the reference state to set
void metaheuristics.generators.MultiobjectiveHillClimbingRestart.setInitialReference(State stateInitialRef)
setInitialReference - set the initial reference state.
stateInitialRef the initial reference state to set
GeneratorType metaheuristics.generators.MultiobjectiveHillClimbingRestart.getGeneratorType()
getGeneratorType - get the generator type.
the generator type
References metaheuristics.generators.MultiobjectiveHillClimbingRestart.generatortype.
void metaheuristics.generators.MultiobjectiveHillClimbingRestart.setGeneratorType(GeneratorType generatortype)
setGeneratorType - set the generator type.
generatortype the generator type to set
References metaheuristics.generators.MultiobjectiveHillClimbingRestart.generatortype.
GeneratorType metaheuristics.generators.MultiobjectiveHillClimbingRestart.getType()
getType - get the generator type.
the generator type
List< State > metaheuristics.generators.MultiobjectiveHillClimbingRestart.getSonList()
getSonList - get the list of child states.
the list of child states
boolean metaheuristics.generators.MultiobjectiveHillClimbingRestart.awardUpdateREF(State stateCandidate)
awardUpdateREF - award the update of the reference state.
stateCandidate return true if the reference state was updated, false otherwise
float metaheuristics.generators.MultiobjectiveHillClimbingRestart.getWeight()
getWeight - get the weight of the generator.
the weight of the generator
void metaheuristics.generators.MultiobjectiveHillClimbingRestart.setWeight(float weight)
setWeight - set the weight of the generator.
weight the weight to set
References metaheuristics.generators.MultiobjectiveHillClimbingRestart.weight.
float[] metaheuristics.generators.MultiobjectiveHillClimbingRestart.getTrace()
getTrace - get the trace of the generator.
the trace of the generator
int[] metaheuristics.generators.MultiobjectiveHillClimbingRestart.getListCountBetterGender()
getListCountBetterGender - get the list of count of better solutions by gender.
the list of count of better solutions by gender
int[] metaheuristics.generators.MultiobjectiveHillClimbingRestart.getListCountGender()
getListCountGender - get the list of count of solutions by gender.
the list of count of solutions by gender
boolean metaheuristics.generators.MultiobjectiveHillClimbingRestart.contain(State state)
contain - check if the state is contained in the visited states.
state return true if the state is contained, false otherwise
References problem.definition.State.Comparator, metaheuristics.generators.MultiobjectiveHillClimbingRestart.visitedState.
Referenced by metaheuristics.generators.MultiobjectiveHillClimbingRestart.updateReference.