metaheuristics::generators::LimitRoulette
float metaheuristics.generators.LimitRoulette.limitLow
Referenced by metaheuristics.generators.LimitRoulette.getLimitLow, metaheuristics.generators.LimitRoulette.setLimitLow.
float metaheuristics.generators.LimitRoulette.limitHigh
Referenced by metaheuristics.generators.LimitRoulette.getLimitHigh, metaheuristics.generators.LimitRoulette.setLimitHigh.
Generator metaheuristics.generators.LimitRoulette.generator
Referenced by metaheuristics.generators.LimitRoulette.getGenerator, metaheuristics.generators.LimitRoulette.setGenerator.
Generator metaheuristics.generators.LimitRoulette.getGenerator()
getGenerator - get the generator associated with the Limit Roulette.
the generator
References metaheuristics.generators.LimitRoulette.generator.
void metaheuristics.generators.LimitRoulette.setGenerator(Generator generator)
setGenerator - set the generator associated with the Limit Roulette.
generator the generator to set
References metaheuristics.generators.LimitRoulette.generator.
Referenced by metaheuristics.generators.MultiGenerator.roulette.
float metaheuristics.generators.LimitRoulette.getLimitHigh()
getLimitHigh - get the upper limit of the Limit Roulette.
the upper limit
References metaheuristics.generators.LimitRoulette.limitHigh.
void metaheuristics.generators.LimitRoulette.setLimitHigh(float limitHigh)
setLimitHigh - set the upper limit of the Limit Roulette.
limitHigh the upper limit to set
References metaheuristics.generators.LimitRoulette.limitHigh.
Referenced by metaheuristics.generators.MultiGenerator.roulette, evolutionary_algorithms.complement.RouletteSelection.selection.
float metaheuristics.generators.LimitRoulette.getLimitLow()
getLimitLow - get the lower limit of the Limit Roulette.
the lower limit
References metaheuristics.generators.LimitRoulette.limitLow.
void metaheuristics.generators.LimitRoulette.setLimitLow(float limitLow)
setLimitLow - set the lower limit of the Limit Roulette.
limitLow the lower limit to set
References metaheuristics.generators.LimitRoulette.limitLow.
Referenced by metaheuristics.generators.MultiGenerator.roulette, evolutionary_algorithms.complement.RouletteSelection.selection.