metaheuristics::generators::MultiCaseSimulatedAnnealing
CandidateValue metaheuristics.generators.MultiCaseSimulatedAnnealing.candidatevalue
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.generate.
AcceptType metaheuristics.generators.MultiCaseSimulatedAnnealing.typeAcceptation
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.updateReference.
StrategyType metaheuristics.generators.MultiCaseSimulatedAnnealing.strategy
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.generate.
CandidateType metaheuristics.generators.MultiCaseSimulatedAnnealing.typeCandidate
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.generate.
State metaheuristics.generators.MultiCaseSimulatedAnnealing.stateReferenceSA
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.generate, metaheuristics.generators.MultiCaseSimulatedAnnealing.getReference, metaheuristics.generators.MultiCaseSimulatedAnnealing.getReferenceList, metaheuristics.generators.MultiCaseSimulatedAnnealing.updateReference.
IFFactoryAcceptCandidate metaheuristics.generators.MultiCaseSimulatedAnnealing.ifacceptCandidate
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.updateReference.
int metaheuristics.generators.MultiCaseSimulatedAnnealing.countRept
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.updateReference.
GeneratorType metaheuristics.generators.MultiCaseSimulatedAnnealing.typeGenerator
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.getTypeGenerator, metaheuristics.generators.MultiCaseSimulatedAnnealing.setTypeGenerator.
List<State> metaheuristics.generators.MultiCaseSimulatedAnnealing.listStateReference
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.getReferenceList.
float metaheuristics.generators.MultiCaseSimulatedAnnealing.weight
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.MultiCaseSimulatedAnnealing, metaheuristics.generators.MultiCaseSimulatedAnnealing.setWeight.
List<Float> metaheuristics.generators.MultiCaseSimulatedAnnealing.listTrace
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.getTrace, metaheuristics.generators.MultiCaseSimulatedAnnealing.MultiCaseSimulatedAnnealing.
final double metaheuristics.generators.MultiCaseSimulatedAnnealing.alpha
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.updateReference.
final Double metaheuristics.generators.MultiCaseSimulatedAnnealing.tfinal
Double metaheuristics.generators.MultiCaseSimulatedAnnealing.tinitial
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.getTinitial, metaheuristics.generators.MultiCaseSimulatedAnnealing.setTinitial.
int metaheuristics.generators.MultiCaseSimulatedAnnealing.countIterationsT
GeneratorType metaheuristics.generators.MultiCaseSimulatedAnnealing.getTypeGenerator()
getTypeGenerator - get the type of the generator.
the type of the generator
References metaheuristics.generators.MultiCaseSimulatedAnnealing.typeGenerator.
void metaheuristics.generators.MultiCaseSimulatedAnnealing.setTypeGenerator(GeneratorType typeGenerator)
setTypeGenerator - set the type of the generator.
typeGenerator the type of the generator to set
References metaheuristics.generators.MultiCaseSimulatedAnnealing.typeGenerator.
metaheuristics.generators.MultiCaseSimulatedAnnealing.MultiCaseSimulatedAnnealing()
MultiCaseSimulatedAnnealing - class that implements the Multi-Case Simulated Annealing metaheuristic.
References local_search.acceptation_type.AcceptType.AcceptMulticase, metaheuristics.generators.MultiCaseSimulatedAnnealing.listTrace, metaheuristics.generators.GeneratorType.MultiCaseSimulatedAnnealing, local_search.complement.StrategyType.NORMAL, local_search.candidate_type.CandidateType.RandomCandidate, metaheuristics.generators.MultiCaseSimulatedAnnealing.weight.
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.updateReference.
State metaheuristics.generators.MultiCaseSimulatedAnnealing.generate(Integer operatornumber)
generate - generate a new state based on the operator number.
operatornumber the operator number to use for generating the new state the generated state
References metaheuristics.generators.MultiCaseSimulatedAnnealing.candidatevalue, problem.definition.Operator.generatedNewState, problem.definition.Problem.getOperator, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.MultiCaseSimulatedAnnealing.stateReferenceSA, metaheuristics.generators.MultiCaseSimulatedAnnealing.strategy, metaheuristics.generators.MultiCaseSimulatedAnnealing.typeCandidate.
State metaheuristics.generators.MultiCaseSimulatedAnnealing.getReference()
getReference - get the reference state.
the reference state
References metaheuristics.generators.MultiCaseSimulatedAnnealing.stateReferenceSA.
void metaheuristics.generators.MultiCaseSimulatedAnnealing.setStateRef(State stateRef)
setStateRef - set the reference state.
stateRef the reference state to set
void metaheuristics.generators.MultiCaseSimulatedAnnealing.setInitialReference(State stateInitialRef)
setInitialReference - set the initial reference state.
stateInitialRef the initial reference state to set
void metaheuristics.generators.MultiCaseSimulatedAnnealing.updateReference(State stateCandidate, Integer countIterationsCurrent)
updateReference - update the reference state based on the candidate state.
stateCandidate countIterationsCurrent
References local_search.acceptation_type.AcceptableCandidate.acceptCandidate, metaheuristics.generators.MultiCaseSimulatedAnnealing.alpha, metaheuristics.generators.MultiCaseSimulatedAnnealing.countRept, metaheuristics.generators.MultiCaseSimulatedAnnealing.getReferenceList, metaheuristics.generators.MultiCaseSimulatedAnnealing.ifacceptCandidate, metaheuristics.generators.MultiCaseSimulatedAnnealing.MultiCaseSimulatedAnnealing, metaheuristics.generators.MultiCaseSimulatedAnnealing.stateReferenceSA, metaheuristics.generators.MultiCaseSimulatedAnnealing.typeAcceptation.
GeneratorType metaheuristics.generators.MultiCaseSimulatedAnnealing.getType()
getType - get the type of the generator.
the type of the generator
List< State > metaheuristics.generators.MultiCaseSimulatedAnnealing.getReferenceList()
getReferenceList - get the list of reference states.
the list of reference states
References metaheuristics.generators.MultiCaseSimulatedAnnealing.listStateReference, metaheuristics.generators.MultiCaseSimulatedAnnealing.stateReferenceSA.
Referenced by metaheuristics.generators.MultiCaseSimulatedAnnealing.updateReference.
List< State > metaheuristics.generators.MultiCaseSimulatedAnnealing.getSonList()
getSonList - get the list of son states.
the list of son states
boolean metaheuristics.generators.MultiCaseSimulatedAnnealing.awardUpdateREF(State stateCandidate)
awardUpdateREF - award the update of the reference state.
stateCandidate return true if the reference state was updated, false otherwise
float metaheuristics.generators.MultiCaseSimulatedAnnealing.getWeight()
getWeight - get the weight of the generator.
the weight of the generator
void metaheuristics.generators.MultiCaseSimulatedAnnealing.setWeight(float weight)
setWeight - set the weight of the generator.
weight the weight to set
References metaheuristics.generators.MultiCaseSimulatedAnnealing.weight.
int[] metaheuristics.generators.MultiCaseSimulatedAnnealing.getListCountBetterGender()
getListCountBetterGender - get the list of counts for better gender.
the list of counts for better gender
int[] metaheuristics.generators.MultiCaseSimulatedAnnealing.getListCountGender()
getListCountGender - get the list of counts for gender.
the list of counts for gender
float[] metaheuristics.generators.MultiCaseSimulatedAnnealing.getTrace()
getTrace - get the trace of the generator.
the trace of the generator
References metaheuristics.generators.MultiCaseSimulatedAnnealing.listTrace.
static Double metaheuristics.generators.MultiCaseSimulatedAnnealing.getTinitial()
References metaheuristics.generators.MultiCaseSimulatedAnnealing.tinitial.
Referenced by local_search.acceptation_type.AcceptMulticase.acceptCandidate.
static void metaheuristics.generators.MultiCaseSimulatedAnnealing.setTinitial(Double t)
setTinitial - set the initial temperature.
t the initial temperature to set
References metaheuristics.generators.MultiCaseSimulatedAnnealing.tinitial.
static int metaheuristics.generators.MultiCaseSimulatedAnnealing.getCountIterationsT()
getCountIterationsT - get the count of iterations for temperature update.
the count of iterations for temperature update
static void metaheuristics.generators.MultiCaseSimulatedAnnealing.setCountIterationsT(int c)
setCountIterationsT - set the count of iterations for temperature update.
c the count of iterations to set