metaheuristics::generators::GeneticAlgorithm
State metaheuristics.generators.GeneticAlgorithm.stateReferenceGA
Referenced by metaheuristics.generators.GeneticAlgorithm.getReference.
List<State> metaheuristics.generators.GeneticAlgorithm.listState
Referenced by metaheuristics.generators.GeneticAlgorithm.generate, metaheuristics.generators.GeneticAlgorithm.getListState, metaheuristics.generators.GeneticAlgorithm.getListStateRef, metaheuristics.generators.GeneticAlgorithm.getReference, metaheuristics.generators.GeneticAlgorithm.getReferenceList, metaheuristics.generators.GeneticAlgorithm.setListState, metaheuristics.generators.GeneticAlgorithm.updateReference.
IFFactoryFatherSelection metaheuristics.generators.GeneticAlgorithm.iffatherselection
Referenced by metaheuristics.generators.GeneticAlgorithm.generate.
IFFactoryCrossover metaheuristics.generators.GeneticAlgorithm.iffactorycrossover
Referenced by metaheuristics.generators.GeneticAlgorithm.generate.
IFFactoryMutation metaheuristics.generators.GeneticAlgorithm.iffactorymutation
Referenced by metaheuristics.generators.GeneticAlgorithm.generate.
IFFactoryReplace metaheuristics.generators.GeneticAlgorithm.iffreplace
Referenced by metaheuristics.generators.GeneticAlgorithm.updateReference.
GeneratorType metaheuristics.generators.GeneticAlgorithm.generatorType
Referenced by metaheuristics.generators.GeneticAlgorithm.getGeneratorType, metaheuristics.generators.GeneticAlgorithm.getType, metaheuristics.generators.GeneticAlgorithm.setGeneratorType.
float metaheuristics.generators.GeneticAlgorithm.weight
Referenced by metaheuristics.generators.GeneticAlgorithm.GeneticAlgorithm, metaheuristics.generators.GeneticAlgorithm.getWeight, metaheuristics.generators.GeneticAlgorithm.setWeight.
int [] metaheuristics.generators.GeneticAlgorithm.listCountBetterGender
Referenced by metaheuristics.generators.GeneticAlgorithm.GeneticAlgorithm, metaheuristics.generators.GeneticAlgorithm.getListCountBetterGender.
int [] metaheuristics.generators.GeneticAlgorithm.listCountGender
Referenced by metaheuristics.generators.GeneticAlgorithm.GeneticAlgorithm, metaheuristics.generators.GeneticAlgorithm.getListCountGender.
float [] metaheuristics.generators.GeneticAlgorithm.listTrace
Referenced by metaheuristics.generators.GeneticAlgorithm.GeneticAlgorithm, metaheuristics.generators.GeneticAlgorithm.getTrace.
final MutationType metaheuristics.generators.GeneticAlgorithm.mutationType
Referenced by metaheuristics.generators.GeneticAlgorithm.generate.
final CrossoverType metaheuristics.generators.GeneticAlgorithm.crossoverType
Referenced by metaheuristics.generators.GeneticAlgorithm.generate.
final ReplaceType metaheuristics.generators.GeneticAlgorithm.replaceType
Referenced by metaheuristics.generators.GeneticAlgorithm.updateReference.
final SelectionType metaheuristics.generators.GeneticAlgorithm.selectionType
Referenced by metaheuristics.generators.GeneticAlgorithm.generate.
final double metaheuristics.generators.GeneticAlgorithm.PC
Referenced by metaheuristics.generators.GeneticAlgorithm.generate.
final double metaheuristics.generators.GeneticAlgorithm.PM
Referenced by metaheuristics.generators.GeneticAlgorithm.generate.
final int metaheuristics.generators.GeneticAlgorithm.countRef
Referenced by metaheuristics.generators.RandomSearch.generate, metaheurictics.strategy.Strategy.update, local_search.complement.UpdateParameter.updateParameter.
final int metaheuristics.generators.GeneticAlgorithm.truncation
Referenced by metaheuristics.generators.GeneticAlgorithm.generate.
metaheuristics.generators.GeneticAlgorithm.GeneticAlgorithm()
GeneticAlgorithm - method to create an instance of GeneticAlgorithm.
References metaheuristics.generators.GeneratorType.GeneticAlgorithm, metaheuristics.generators.GeneticAlgorithm.getListStateRef, metaheuristics.generators.GeneticAlgorithm.listCountBetterGender, metaheuristics.generators.GeneticAlgorithm.listCountGender, metaheuristics.generators.GeneticAlgorithm.listTrace, metaheuristics.generators.GeneticAlgorithm.weight.
Referenced by metaheuristics.generators.GeneticAlgorithm.getListStateRef.
State metaheuristics.generators.GeneticAlgorithm.generate(Integer operatornumber)
Uses ThreadLocalRandom for algorithmic (non-cryptographic) randomness.
This RNG is used to decide whether a mutation occurs in the evolutionary algorithm and is not used for security-sensitive purposes. Suppress Sonar security hotspot S2245 for this usage. generate - method to generate a new state. operatornumber
References evolutionary_algorithms.complement.Crossover.crossover, metaheuristics.generators.GeneticAlgorithm.crossoverType, problem.definition.State.getCopy, metaheurictics.strategy.Strategy.getProblem, problem.definition.Problem.getState, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.GeneticAlgorithm.iffactorycrossover, metaheuristics.generators.GeneticAlgorithm.iffactorymutation, metaheuristics.generators.GeneticAlgorithm.iffatherselection, metaheuristics.generators.GeneticAlgorithm.listState, evolutionary_algorithms.complement.Mutation.mutation, metaheuristics.generators.GeneticAlgorithm.mutationType, metaheuristics.generators.GeneticAlgorithm.PC, metaheuristics.generators.GeneticAlgorithm.PM, evolutionary_algorithms.complement.FatherSelection.selection, metaheuristics.generators.GeneticAlgorithm.selectionType, problem.definition.State.setCode, problem.definition.State.setEvaluation, problem.definition.State.setNumber, problem.definition.State.setTypeGenerator, metaheuristics.generators.GeneticAlgorithm.truncation.
State metaheuristics.generators.GeneticAlgorithm.getReference()
getReference - method to get the current reference state.
returns the current reference state.
References metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, problem.definition.Problem.getTypeProblem, metaheuristics.generators.GeneticAlgorithm.listState, problem.definition.Problem.ProblemType.Maximizar, metaheuristics.generators.GeneticAlgorithm.stateReferenceGA.
void metaheuristics.generators.GeneticAlgorithm.setStateRef(State stateRef)
setStateRef - method to set the current reference state.
stateRef
void metaheuristics.generators.GeneticAlgorithm.setInitialReference(State stateInitialRef)
setInitialReference - method to set the initial reference state.
stateInitialRef
void metaheuristics.generators.GeneticAlgorithm.updateReference(State stateCandidate, Integer countIterationsCurrent)
updateReference - method to update the current reference state.
stateCandidate countIterationsCurrent
References metaheuristics.generators.GeneticAlgorithm.iffreplace, metaheuristics.generators.GeneticAlgorithm.listState, evolutionary_algorithms.complement.Replace.replace, metaheuristics.generators.GeneticAlgorithm.replaceType.
List< State > metaheuristics.generators.GeneticAlgorithm.getListState()
getListState - method to get the current list of states.
returns the current list of states.
References metaheuristics.generators.GeneticAlgorithm.listState.
Referenced by metaheuristics.generators.GeneticAlgorithm.getListStateRef.
void metaheuristics.generators.GeneticAlgorithm.setListState(List< State > listState)
setListState - method to set the current list of states.
listState
References metaheuristics.generators.GeneticAlgorithm.listState.
List< State > metaheuristics.generators.GeneticAlgorithm.getListStateRef()
getListStateRef - method to get the current list of reference states.
returns the current list of reference states.
References metaheuristics.generators.GeneratorType.GeneticAlgorithm, metaheuristics.generators.GeneticAlgorithm.GeneticAlgorithm, metaheurictics.strategy.Strategy.getListKey, metaheuristics.generators.GeneticAlgorithm.getListState, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.GeneticAlgorithm.listState, metaheuristics.generators.RandomSearch.listStateReference, metaheurictics.strategy.Strategy.mapGenerators.
Referenced by metaheuristics.generators.GeneticAlgorithm.GeneticAlgorithm.
GeneratorType metaheuristics.generators.GeneticAlgorithm.getGeneratorType()
getGeneratorType - method to get the generator type.
returns the generator type.
References metaheuristics.generators.GeneticAlgorithm.generatorType.
void metaheuristics.generators.GeneticAlgorithm.setGeneratorType(GeneratorType generatorType)
setGeneratorType - method to set the generator type.
generatorType
References metaheuristics.generators.GeneticAlgorithm.generatorType.
GeneratorType metaheuristics.generators.GeneticAlgorithm.getType()
getType - method to get the generator type.
returns the generator type.
References metaheuristics.generators.GeneticAlgorithm.generatorType.
List< State > metaheuristics.generators.GeneticAlgorithm.getReferenceList()
getReferenceList - method to get the current list of reference states.
returns the current list of reference states.
References metaheuristics.generators.GeneticAlgorithm.listState.
List< State > metaheuristics.generators.GeneticAlgorithm.getSonList()
getSonList - method to get the current list of son states.
returns the current list of son states.
boolean metaheuristics.generators.GeneticAlgorithm.awardUpdateREF(State stateCandidate)
awardUpdateREF - method to award the update of the reference state.
stateCandidate returns true if the update is awarded, false otherwise.
float metaheuristics.generators.GeneticAlgorithm.getWeight()
getWeight - method to get the weight.
returns the weight.
References metaheuristics.generators.GeneticAlgorithm.weight.
void metaheuristics.generators.GeneticAlgorithm.setWeight(float weight)
setWeight - method to set the weight.
weight
References metaheuristics.generators.GeneticAlgorithm.weight.
int[] metaheuristics.generators.GeneticAlgorithm.getListCountBetterGender()
getListCountBetterGender - method to get the list of count better gender.
returns the list of count better gender.
References metaheuristics.generators.GeneticAlgorithm.listCountBetterGender.
int[] metaheuristics.generators.GeneticAlgorithm.getListCountGender()
getListCountGender - method to get the list of count gender.
returns the list of count gender.
References metaheuristics.generators.GeneticAlgorithm.listCountGender.
float[] metaheuristics.generators.GeneticAlgorithm.getTrace()
getTrace - method to get the trace.
returns the trace.
References metaheuristics.generators.GeneticAlgorithm.listTrace.