metaheuristics::generators::ParticleSwarmOptimization
State metaheuristics.generators.ParticleSwarmOptimization.stateReferencePSO
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getStateReferencePSO, metaheuristics.generators.ParticleSwarmOptimization.setStateReferencePSO.
List<State> metaheuristics.generators.ParticleSwarmOptimization.listStateReference
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getReferenceList, metaheuristics.generators.ParticleSwarmOptimization.setListStateReference, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
List<Particle> metaheuristics.generators.ParticleSwarmOptimization.listParticle
Referenced by metaheuristics.generators.ParticleSwarmOptimization.generate, metaheuristics.generators.ParticleSwarmOptimization.getListParticle, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization, metaheuristics.generators.ParticleSwarmOptimization.setListParticle, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
GeneratorType metaheuristics.generators.ParticleSwarmOptimization.generatorType
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getGeneratorType, metaheuristics.generators.ParticleSwarmOptimization.getType, metaheuristics.generators.ParticleSwarmOptimization.setGeneratorType.
float metaheuristics.generators.ParticleSwarmOptimization.weight
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getWeight, metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization, metaheuristics.generators.ParticleSwarmOptimization.setWeight.
int [] metaheuristics.generators.ParticleSwarmOptimization.listCountBetterGender
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getListCountBetterGender, metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization.
int [] metaheuristics.generators.ParticleSwarmOptimization.listCountGender
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getListCountGender, metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization.
float [] metaheuristics.generators.ParticleSwarmOptimization.listTrace
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getTrace, metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization.
int metaheuristics.generators.ParticleSwarmOptimization.countParticle
double metaheuristics.generators.ParticleSwarmOptimization.constriction
State [] metaheuristics.generators.ParticleSwarmOptimization.lBest
State metaheuristics.generators.ParticleSwarmOptimization.gBest
int metaheuristics.generators.ParticleSwarmOptimization.countCurrentIterPSO
int metaheuristics.generators.ParticleSwarmOptimization.coutSwarm
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getCoutSwarm, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization, metaheuristics.generators.ParticleSwarmOptimization.setCountParticleBySwarm, metaheuristics.generators.ParticleSwarmOptimization.setCoutSwarm.
int metaheuristics.generators.ParticleSwarmOptimization.countParticleBySwarm
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getCountParticleBySwarm, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, metaheuristics.generators.ParticleSwarmOptimization.setCountParticleBySwarm, metaheuristics.generators.ParticleSwarmOptimization.setCoutSwarm, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
int metaheuristics.generators.ParticleSwarmOptimization.countRef
Referenced by metaheuristics.generators.ParticleSwarmOptimization.generate, metaheuristics.generators.ParticleSwarmOptimization.getCountRef, metaheuristics.generators.ParticleSwarmOptimization.getListStateRef, metaheuristics.generators.ParticleSwarmOptimization.setCountRef.
final double metaheuristics.generators.ParticleSwarmOptimization.wmax
Referenced by metaheuristics.generators.Particle.UpdateVelocity.
final double metaheuristics.generators.ParticleSwarmOptimization.wmin
Referenced by metaheuristics.generators.Particle.UpdateVelocity.
final int metaheuristics.generators.ParticleSwarmOptimization.learning1
Referenced by metaheuristics.generators.Particle.UpdateVelocity.
final int metaheuristics.generators.ParticleSwarmOptimization.learning2
Referenced by metaheuristics.generators.Particle.UpdateVelocity.
final boolean metaheuristics.generators.ParticleSwarmOptimization.binary
Referenced by metaheuristics.generators.Particle.UpdateCode.
static int metaheuristics.generators.ParticleSwarmOptimization.getCoutSwarm()
getCoutSwarm - get the number of swarms.
return the number of swarms
References metaheuristics.generators.ParticleSwarmOptimization.coutSwarm.
static void metaheuristics.generators.ParticleSwarmOptimization.setCoutSwarm(int v)
setCoutSwarm - set the number of swarms.
v the number of swarms to set
References metaheuristics.generators.ParticleSwarmOptimization.countParticleBySwarm, metaheuristics.generators.ParticleSwarmOptimization.coutSwarm, metaheuristics.generators.ParticleSwarmOptimization.setCountRef.
static int metaheuristics.generators.ParticleSwarmOptimization.getCountParticleBySwarm()
getCountParticleBySwarm - get the number of particles per swarm.
the number of particles per swarm
References metaheuristics.generators.ParticleSwarmOptimization.countParticleBySwarm.
static void metaheuristics.generators.ParticleSwarmOptimization.setCountParticleBySwarm(int v)
setCountParticleBySwarm - set the number of particles per swarm.
v the number of particles per swarm to set
References metaheuristics.generators.ParticleSwarmOptimization.countParticleBySwarm, metaheuristics.generators.ParticleSwarmOptimization.coutSwarm, metaheuristics.generators.ParticleSwarmOptimization.setCountRef.
static State[] metaheuristics.generators.ParticleSwarmOptimization.getLBest()
static void metaheuristics.generators.ParticleSwarmOptimization.setLBest(State[] arr)
setLBest - set the local best array.
arr
References problem.definition.State.clone.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization.
static void metaheuristics.generators.ParticleSwarmOptimization.setLBestAt(int idx, State s)
setLBest - set the local best at index.
idx s
References problem.definition.State.clone.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.updateReference.
static State metaheuristics.generators.ParticleSwarmOptimization.getGBest()
Referenced by metaheuristics.generators.ParticleSwarmOptimization.updateReference.
static void metaheuristics.generators.ParticleSwarmOptimization.setGBest(State s)
Referenced by metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
static int metaheuristics.generators.ParticleSwarmOptimization.getCountCurrentIterPSO()
Referenced by metaheuristics.generators.ParticleSwarmOptimization.updateReference, metaheuristics.generators.Particle.UpdateVelocity.
static void metaheuristics.generators.ParticleSwarmOptimization.setCountCurrentIterPSO(int v)
Referenced by metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
static int metaheuristics.generators.ParticleSwarmOptimization.getCountParticle()
Referenced by metaheuristics.generators.ParticleSwarmOptimization.generate, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
static void metaheuristics.generators.ParticleSwarmOptimization.setCountParticle(int v)
Referenced by metaheuristics.generators.ParticleSwarmOptimization.generate, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization, metaheuristics.generators.ParticleSwarmOptimization.updateReference.
static int metaheuristics.generators.ParticleSwarmOptimization.getCountRef()
References metaheuristics.generators.ParticleSwarmOptimization.countRef.
Referenced by metaheuristics.generators.RandomSearch.generate, metaheurictics.strategy.Strategy.update, local_search.complement.UpdateParameter.updateParameter.
static void metaheuristics.generators.ParticleSwarmOptimization.setCountRef(int countRef)
References metaheuristics.generators.ParticleSwarmOptimization.countRef.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.setCountParticleBySwarm, metaheuristics.generators.ParticleSwarmOptimization.setCoutSwarm.
metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization()
Create a new ParticleSwarmOptimization instance.
The constructor initializes internal arrays and sets default values for weights, counters and generators. It intentionally does not perform expensive operations; heavy initialization is deferred to getListStateRef() when needed.
References metaheuristics.generators.ParticleSwarmOptimization.coutSwarm, metaheuristics.generators.ParticleSwarmOptimization.gBestInicial, metaheuristics.generators.ParticleSwarmOptimization.getListStateRef, metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest, metaheuristics.generators.ParticleSwarmOptimization.listCountBetterGender, metaheuristics.generators.ParticleSwarmOptimization.listCountGender, metaheuristics.generators.ParticleSwarmOptimization.listParticle, metaheuristics.generators.ParticleSwarmOptimization.listTrace, metaheuristics.generators.GeneratorType.ParticleSwarmOptimization, metaheuristics.generators.ParticleSwarmOptimization.setCountCurrentIterPSO, metaheuristics.generators.ParticleSwarmOptimization.setCountParticle, metaheuristics.generators.ParticleSwarmOptimization.setGBest, metaheuristics.generators.ParticleSwarmOptimization.setLBest, metaheuristics.generators.ParticleSwarmOptimization.setListParticle, metaheuristics.generators.ParticleSwarmOptimization.weight.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getListStateRef.
State metaheuristics.generators.ParticleSwarmOptimization.generate(Integer operatornumber)
Generate a new state by advancing the next particle in the swarm.
operatornumber unused for PSO (kept for API compatibility) the newly generated State produced by the advanced particle ReflectiveOperationException forwarded from nested generator calls
References metaheuristics.generators.ParticleSwarmOptimization.countRef, metaheuristics.generators.ParticleSwarmOptimization.getCountParticle, metaheuristics.generators.ParticleSwarmOptimization.listParticle, metaheuristics.generators.ParticleSwarmOptimization.setCountParticle.
void metaheuristics.generators.ParticleSwarmOptimization.inicialiceLBest()
Initialize the local best lBest array for each swarm.
The method inspects particle personal-bests within each swarm and selects the best among them according to the problem's objective type (maximize or minimize).
References metaheuristics.generators.ParticleSwarmOptimization.countParticleBySwarm, metaheuristics.generators.ParticleSwarmOptimization.coutSwarm, metaheuristics.generators.ParticleSwarmOptimization.getCountParticle, problem.definition.State.getEvaluation, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, problem.definition.Problem.getTypeProblem, metaheuristics.generators.ParticleSwarmOptimization.listParticle, problem.definition.Problem.ProblemType.Maximizar, metaheuristics.generators.ParticleSwarmOptimization.setCountParticle.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization.
State metaheuristics.generators.ParticleSwarmOptimization.getReference()
Return the single reference state used by single-reference generators.
PSO manages multiple references (per-swarm and global), so this method returns null by design in the current implementation. null in this PSO implementation
State metaheuristics.generators.ParticleSwarmOptimization.getStateReferencePSO()
Return the PSO-specific reference state used by some helpers.
stored stateReferencePSO (may be null)
References metaheuristics.generators.ParticleSwarmOptimization.stateReferencePSO.
void metaheuristics.generators.ParticleSwarmOptimization.setStateReferencePSO(State stateReferencePSO)
Set the PSO-specific reference state.
A defensive copy is not performed because State provides its own copy/clone methods; callers should clone if they want isolation. stateReferencePSO the state to store as PSO reference
References metaheuristics.generators.ParticleSwarmOptimization.stateReferencePSO.
List< Particle > metaheuristics.generators.ParticleSwarmOptimization.getListStateReference()
Return the current list of particles used internally.
The returned list is the internal storage reference; callers that need mutability isolation should copy it. internal list of particles
References metaheuristics.generators.ParticleSwarmOptimization.getListParticle.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getListStateRef.
void metaheuristics.generators.ParticleSwarmOptimization.setListStateReference(List< State > listStateReference)
Replace the internal state reference list.
Provided for API compatibility; most callers should use setListParticle instead. listStateReference new list of states
References metaheuristics.generators.ParticleSwarmOptimization.listStateReference.
List< Particle > metaheuristics.generators.ParticleSwarmOptimization.getListParticle()
Get the internal particle list.
internal list of Particle instances
References metaheuristics.generators.ParticleSwarmOptimization.listParticle.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getListStateRef, metaheuristics.generators.ParticleSwarmOptimization.getListStateReference.
List< Particle > metaheuristics.generators.ParticleSwarmOptimization.setListParticle(List< Particle > listParticle)
Replace the internal particle list and return the newly set list.
listParticle list to install the installed list
References metaheuristics.generators.ParticleSwarmOptimization.listParticle.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.getListStateRef, metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization.
GeneratorType metaheuristics.generators.ParticleSwarmOptimization.getGeneratorType()
Get the generator type associated with this instance.
generator type (ParticleSwarmOptimization)
References metaheuristics.generators.ParticleSwarmOptimization.generatorType.
void metaheuristics.generators.ParticleSwarmOptimization.setGeneratorType(GeneratorType generatorType)
Set the generator type for this instance.
generatorType generator type to set
References metaheuristics.generators.ParticleSwarmOptimization.generatorType.
void metaheuristics.generators.ParticleSwarmOptimization.updateReference(State stateCandidate, Integer countIterationsCurrent)
Update the PSO internal references based on a newly generated candidate state.
This method updates the particle personal-bests and possibly the local/global bests depending on the objective. stateCandidate newly generated candidate state countIterationsCurrent current iteration counter ReflectiveOperationException forwarded from nested calls
References metaheuristics.generators.ParticleSwarmOptimization.countParticleBySwarm, metaheuristics.generators.ParticleSwarmOptimization.getCountCurrentIterPSO, metaheuristics.generators.ParticleSwarmOptimization.getCountParticle, problem.definition.State.getEvaluation, metaheuristics.generators.ParticleSwarmOptimization.getGBest, metaheurictics.strategy.Strategy.getProblem, metaheuristics.generators.ParticleSwarmOptimization.getReferenceList, metaheuristics.generators.Particle.getStatePBest, metaheurictics.strategy.Strategy.getStrategy, problem.definition.Problem.getTypeProblem, metaheuristics.generators.ParticleSwarmOptimization.listParticle, metaheuristics.generators.ParticleSwarmOptimization.listStateReference, problem.definition.Problem.ProblemType.Maximizar, problem.definition.State.setCode, metaheuristics.generators.ParticleSwarmOptimization.setCountCurrentIterPSO, metaheuristics.generators.ParticleSwarmOptimization.setCountParticle, problem.definition.State.setEvaluation, metaheuristics.generators.ParticleSwarmOptimization.setGBest, metaheuristics.generators.ParticleSwarmOptimization.setLBestAt, problem.definition.State.setTypeGenerator, metaheuristics.generators.Particle.updateReference.
State metaheuristics.generators.ParticleSwarmOptimization.gBestInicial()
Compute the initial global best (gBest) from the local bests contained in lBest.
the best State among lBest
References problem.definition.State.getEvaluation, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, problem.definition.Problem.getTypeProblem, problem.definition.Problem.ProblemType.Maximizar.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization.
void metaheuristics.generators.ParticleSwarmOptimization.setInitialReference(State stateInitialRef)
Set the initial reference(s) for the generator.
PSO uses swarm references and therefore this method is intentionally left as a no-op or to be implemented by callers that bridge different data. stateInitialRef initial state to use as a reference
GeneratorType metaheuristics.generators.ParticleSwarmOptimization.getType()
Return the concrete generator type of this generator.
the GeneratorType for this generator
References metaheuristics.generators.ParticleSwarmOptimization.generatorType.
List< State > metaheuristics.generators.ParticleSwarmOptimization.getReferenceList()
Return a copy of the list used as reference solutions by PSO.
copy of internal reference list
References metaheuristics.generators.ParticleSwarmOptimization.listStateReference.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.updateReference.
List< State > metaheuristics.generators.ParticleSwarmOptimization.getSonList()
Return the currently generated offspring/state list for this generator.
PSO does not maintain a son list in the classical sense and thus returns null. null for PSO
boolean metaheuristics.generators.ParticleSwarmOptimization.awardUpdateREF(State stateCandidate)
Decide whether the provided candidate should update references.
PSO uses updateReference directly; this helper returns false by default and can be implemented if integration requires it. stateCandidate candidate state to evaluate false by default
void metaheuristics.generators.ParticleSwarmOptimization.setWeight(float weight)
Set the internal inertia weight used by particle velocity updates.
weight inertia weight value
References metaheuristics.generators.ParticleSwarmOptimization.weight.
float metaheuristics.generators.ParticleSwarmOptimization.getWeight()
Get the current inertia weight used in PSO.
current weight value
References metaheuristics.generators.ParticleSwarmOptimization.weight.
int[] metaheuristics.generators.ParticleSwarmOptimization.getListCountBetterGender()
Return a defensive copy of the counters that track how many times a particle improved during a period.
copy of listCountBetterGender
References metaheuristics.generators.ParticleSwarmOptimization.listCountBetterGender.
int[] metaheuristics.generators.ParticleSwarmOptimization.getListCountGender()
Return a defensive copy of usage counters per period.
copy of listCountGender
References metaheuristics.generators.ParticleSwarmOptimization.listCountGender.
float[] metaheuristics.generators.ParticleSwarmOptimization.getTrace()
Return a copy of the internal trace array used for diagnostic information (weights over time, etc.).
copy of listTrace
References metaheuristics.generators.ParticleSwarmOptimization.listTrace.
List< Particle > metaheuristics.generators.ParticleSwarmOptimization.getListStateRef()
Build or return the list of Particle instances used by PSO.
If an existing PSO generator instance has an initialized particle list, that list is reused. Otherwise, states from RandomSearch#listStateReference are converted into particles. list of particles representing the swarm population
References metaheuristics.generators.ParticleSwarmOptimization.countRef, metaheurictics.strategy.Strategy.getListKey, metaheuristics.generators.ParticleSwarmOptimization.getListParticle, metaheuristics.generators.ParticleSwarmOptimization.getListStateReference, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.RandomSearch.listStateReference, metaheurictics.strategy.Strategy.mapGenerators, metaheuristics.generators.GeneratorType.ParticleSwarmOptimization, metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization, problem.definition.State.setCode, problem.definition.State.setEvaluation, metaheuristics.generators.ParticleSwarmOptimization.setListParticle.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.ParticleSwarmOptimization.