evolutionary_algorithms::complement::FatherSelection
abstract List< State > evolutionary_algorithms.complement.FatherSelection.selection(List< State > listState, int truncation)
selection - selects the best fathers from the population.
listState truncation returns a list of selected fathers
Referenced by metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.GeneticAlgorithm.generate, metaheuristics.generators.DistributionEstimationAlgorithm.getfathersList.