metaheuristics::generators::Particle
State metaheuristics.generators.Particle.statePBest
Referenced by metaheuristics.generators.Particle.getStatePBest, metaheuristics.generators.Particle.Particle, metaheuristics.generators.Particle.setStatePBest, metaheuristics.generators.Particle.updateReference.
State metaheuristics.generators.Particle.stateActual
Referenced by metaheuristics.generators.Particle.getStateActual, metaheuristics.generators.Particle.Particle, metaheuristics.generators.Particle.setStateActual, metaheuristics.generators.Particle.UpdateCode, metaheuristics.generators.Particle.updateReference.
ArrayList<Object> metaheuristics.generators.Particle.velocity
Referenced by metaheuristics.generators.Particle.getVelocity, metaheuristics.generators.Particle.Particle, metaheuristics.generators.Particle.setVelocity, metaheuristics.generators.Particle.UpdateVelocity.
metaheuristics.generators.Particle.Particle()
Particle - method constructor.
metaheuristics.generators.Particle.Particle(State statePBest, State stateActual, ArrayList< Object > velocity)
Particle - method constructor.
statePBest stateActual velocity
References metaheuristics.generators.Particle.stateActual, metaheuristics.generators.Particle.statePBest, metaheuristics.generators.Particle.velocity.
ArrayList< Object > metaheuristics.generators.Particle.getVelocity()
getVelocity - get the velocity of the particle.
the velocity of the particle
References metaheuristics.generators.Particle.velocity.
void metaheuristics.generators.Particle.setVelocity(ArrayList< Object > velocity)
setVelocity - set the velocity of the particle.
velocity the velocity to set
References metaheuristics.generators.Particle.velocity.
State metaheuristics.generators.Particle.getStatePBest()
getStatePBest - get the personal best state of the particle.
the personal best state of the particle
References metaheuristics.generators.Particle.statePBest.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.updateReference.
void metaheuristics.generators.Particle.setStatePBest(State statePBest)
setStatePBest - set the personal best state of the particle.
statePBest the personal best state to set
References metaheuristics.generators.Particle.statePBest.
State metaheuristics.generators.Particle.getStateActual()
getStateActual - get the current state of the particle.
the current state of the particle
References metaheuristics.generators.Particle.stateActual.
void metaheuristics.generators.Particle.setStateActual(State stateActual)
setStateActual - set the current state of the particle.
stateActual the current state to set
References metaheuristics.generators.Particle.stateActual.
State metaheuristics.generators.Particle.generate(Integer operatornumber)
generate - generate a new state for the particle.
operatornumber IllegalArgumentException SecurityException ClassNotFoundException InstantiationException IllegalAccessException InvocationTargetException NoSuchMethodException
References problem.definition.State.setCode, metaheuristics.generators.Particle.UpdateCode, metaheuristics.generators.Particle.UpdateVelocity.
void metaheuristics.generators.Particle.updateReference(State stateCandidate, Integer countIterationsCurrent)
updateReference - update the reference state and the personal best state of the particle.
stateCandidate countIterationsCurrent IllegalArgumentException SecurityException ClassNotFoundException InstantiationException IllegalAccessException InvocationTargetException NoSuchMethodException
References metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, problem.definition.Problem.getTypeProblem, problem.definition.Problem.ProblemType.Maximizar, metaheuristics.generators.Particle.stateActual, metaheuristics.generators.Particle.statePBest.
Referenced by metaheuristics.generators.ParticleSwarmOptimization.updateReference.
State metaheuristics.generators.Particle.getReference()
getReference - get the reference state.
reference state
void metaheuristics.generators.Particle.setInitialReference(State stateInitialRef)
setInitialReference - set the initial reference state for the particle.
stateInitialRef
GeneratorType metaheuristics.generators.Particle.getType()
getType - get the type of the generator.
return the type of the generator
List< State > metaheuristics.generators.Particle.getReferenceList()
getReferenceList - get the list of reference states.
list of reference states
List< State > metaheuristics.generators.Particle.getSonList()
getSonList - get the list of son states.
list of son states
boolean metaheuristics.generators.Particle.awardUpdateREF(State stateCandidate)
awardUpdateREF - award the update of the reference state.
stateCandidate return true if the reference state was updated, false otherwise
void metaheuristics.generators.Particle.setWeight(float weight)
setWeight - set the weight of the particle.
weight
float metaheuristics.generators.Particle.getWeight()
getWeight - get the weight of the particle.
return the weight of the particle
float[] metaheuristics.generators.Particle.getTrace()
getTrace - get the trace of the particle.
return the trace of the particle
int[] metaheuristics.generators.Particle.getListCountBetterGender()
getListCountBetterGender - get the list of counts of better genders.
list of counts of better genders
int[] metaheuristics.generators.Particle.getListCountGender()
getListCountGender - get the list of counts of genders.
list of counts of genders
ArrayList< Object > metaheuristics.generators.Particle.UpdateVelocity()
Uses ThreadLocalRandom for algorithmic (non-cryptographic) randomness.
This RNG updates particle velocity and is not security-sensitive. Suppress Sonar hotspot S2245 for this usage.
References metaheuristics.generators.ParticleSwarmOptimization.getCountCurrentIterPSO, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.ParticleSwarmOptimization.learning1, metaheuristics.generators.ParticleSwarmOptimization.learning2, metaheuristics.generators.Particle.UpdateVelocity, metaheuristics.generators.Particle.velocity, metaheuristics.generators.ParticleSwarmOptimization.wmax, metaheuristics.generators.ParticleSwarmOptimization.wmin.
Referenced by metaheuristics.generators.Particle.generate, metaheuristics.generators.Particle.UpdateVelocity.
ArrayList< Object > metaheuristics.generators.Particle.UpdateCode(ArrayList< Object > actualVelocity)
Uses ThreadLocalRandom for algorithmic (non-cryptographic) randomness when computing binary code updates.
Not security-sensitive; suppress S2245.
References metaheuristics.generators.ParticleSwarmOptimization.binary, metaheuristics.generators.Particle.stateActual, metaheuristics.generators.Particle.UpdateCode.
Referenced by metaheuristics.generators.Particle.generate, metaheuristics.generators.Particle.UpdateCode.