metaheuristics::generators::DistributionEstimationAlgorithm
State metaheuristics.generators.DistributionEstimationAlgorithm.stateReferenceDA
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getReference.
List<State> metaheuristics.generators.DistributionEstimationAlgorithm.referenceList
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getListReference, metaheuristics.generators.DistributionEstimationAlgorithm.getListStateRef, metaheuristics.generators.DistributionEstimationAlgorithm.getReference, metaheuristics.generators.DistributionEstimationAlgorithm.getReferenceList, metaheuristics.generators.DistributionEstimationAlgorithm.setListReference, metaheuristics.generators.DistributionEstimationAlgorithm.updateReference.
IFFactoryFatherSelection metaheuristics.generators.DistributionEstimationAlgorithm.iffatherselection
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getfathersList.
IFFSampling metaheuristics.generators.DistributionEstimationAlgorithm.iffsampling
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.generate.
IFFactoryReplace metaheuristics.generators.DistributionEstimationAlgorithm.iffreplace
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.updateReference.
DistributionType metaheuristics.generators.DistributionEstimationAlgorithm.distributionType
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getDistributionType, metaheuristics.generators.DistributionEstimationAlgorithm.setDistributionType.
SamplingType metaheuristics.generators.DistributionEstimationAlgorithm.Samplingtype
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.generate.
GeneratorType metaheuristics.generators.DistributionEstimationAlgorithm.generatorType
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getGeneratorType, metaheuristics.generators.DistributionEstimationAlgorithm.setGeneratorType.
float metaheuristics.generators.DistributionEstimationAlgorithm.weight
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.DistributionEstimationAlgorithm, metaheuristics.generators.DistributionEstimationAlgorithm.setWeight.
int [] metaheuristics.generators.DistributionEstimationAlgorithm.listCountBetterGender
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.DistributionEstimationAlgorithm.
int [] metaheuristics.generators.DistributionEstimationAlgorithm.listCountGender
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.DistributionEstimationAlgorithm.
float [] metaheuristics.generators.DistributionEstimationAlgorithm.listTrace
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.DistributionEstimationAlgorithm.
final List<State> metaheuristics.generators.DistributionEstimationAlgorithm.sonList
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getSonList.
final ReplaceType metaheuristics.generators.DistributionEstimationAlgorithm.replaceType
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.updateReference.
final SelectionType metaheuristics.generators.DistributionEstimationAlgorithm.selectionType
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getfathersList.
final int metaheuristics.generators.DistributionEstimationAlgorithm.truncation
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getfathersList.
final int metaheuristics.generators.DistributionEstimationAlgorithm.countRef
Referenced by metaheuristics.generators.RandomSearch.generate, metaheurictics.strategy.Strategy.update, local_search.complement.UpdateParameter.updateParameter.
metaheuristics.generators.DistributionEstimationAlgorithm.DistributionEstimationAlgorithm()
DistributionEstimationAlgorithm - constructor for distribution estimation algorithms.
References metaheuristics.generators.GeneratorType.DistributionEstimationAlgorithm, metaheuristics.generators.DistributionEstimationAlgorithm.getListStateRef, metaheuristics.generators.DistributionEstimationAlgorithm.listCountBetterGender, metaheuristics.generators.DistributionEstimationAlgorithm.listCountGender, metaheuristics.generators.DistributionEstimationAlgorithm.listTrace, evolutionary_algorithms.complement.SamplingType.ProbabilisticSampling, evolutionary_algorithms.complement.DistributionType.Univariate, metaheuristics.generators.DistributionEstimationAlgorithm.weight.
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getListStateRef.
State metaheuristics.generators.DistributionEstimationAlgorithm.maxValue(List< State > listInd)
maxValue - method to find the state with the maximum value.
listInd returns the state with the maximum evaluation value.
References problem.definition.State.getEvaluation.
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.generate.
State metaheuristics.generators.DistributionEstimationAlgorithm.generate(Integer operatornumber)
generate - method to generate a new state.
operatornumber returns the generated state.
References metaheuristics.generators.DistributionEstimationAlgorithm.getfathersList, problem.definition.Problem.getFunction, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.DistributionEstimationAlgorithm.iffsampling, metaheuristics.generators.DistributionEstimationAlgorithm.maxValue, evolutionary_algorithms.complement.Sampling.sampling, metaheuristics.generators.DistributionEstimationAlgorithm.Samplingtype.
State metaheuristics.generators.DistributionEstimationAlgorithm.getReference()
getReference - method to get the current reference state.
returns the current reference state.
References metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, problem.definition.Problem.getTypeProblem, problem.definition.Problem.ProblemType.Maximizar, metaheuristics.generators.DistributionEstimationAlgorithm.referenceList, metaheuristics.generators.DistributionEstimationAlgorithm.stateReferenceDA.
List< State > metaheuristics.generators.DistributionEstimationAlgorithm.getReferenceList()
getReferenceList - method to get the list of reference states.
returns the list of reference states.
References metaheuristics.generators.DistributionEstimationAlgorithm.referenceList.
GeneratorType metaheuristics.generators.DistributionEstimationAlgorithm.getType()
getType - method to get the generator type.
returns the generator type.
void metaheuristics.generators.DistributionEstimationAlgorithm.setInitialReference(State stateInitialRef)
setInitialReference - method to set the initial reference state.
stateInitialRef
void metaheuristics.generators.DistributionEstimationAlgorithm.updateReference(State stateCandidate, Integer countIterationsCurrent)
updateReference - method to update the reference state.
stateCandidate countIterationsCurrent
References metaheuristics.generators.DistributionEstimationAlgorithm.iffreplace, metaheuristics.generators.DistributionEstimationAlgorithm.referenceList, evolutionary_algorithms.complement.Replace.replace, metaheuristics.generators.DistributionEstimationAlgorithm.replaceType.
List< State > metaheuristics.generators.DistributionEstimationAlgorithm.getListStateRef()
getListStateRef - method to get the list of reference states.
returns the list of reference states.
References metaheuristics.generators.DistributionEstimationAlgorithm.DistributionEstimationAlgorithm, metaheuristics.generators.GeneratorType.DistributionEstimationAlgorithm, metaheurictics.strategy.Strategy.getListKey, metaheuristics.generators.DistributionEstimationAlgorithm.getListReference, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.RandomSearch.listStateReference, metaheurictics.strategy.Strategy.mapGenerators, metaheuristics.generators.DistributionEstimationAlgorithm.referenceList.
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.DistributionEstimationAlgorithm.
List< State > metaheuristics.generators.DistributionEstimationAlgorithm.getListReference()
getListReference - method to get the list of reference states.
returns the list of reference states.
References metaheuristics.generators.DistributionEstimationAlgorithm.referenceList.
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.getListStateRef.
void metaheuristics.generators.DistributionEstimationAlgorithm.setListReference(List< State > listReference)
setListReference - method to set the list of reference states.
listReference
References metaheuristics.generators.DistributionEstimationAlgorithm.referenceList.
GeneratorType metaheuristics.generators.DistributionEstimationAlgorithm.getGeneratorType()
getGeneratorType - method to get the generator type.
returns the generator type.
References metaheuristics.generators.DistributionEstimationAlgorithm.generatorType.
void metaheuristics.generators.DistributionEstimationAlgorithm.setGeneratorType(GeneratorType generatorType)
setGeneratorType - method to set the generator type.
generatorType
References metaheuristics.generators.DistributionEstimationAlgorithm.generatorType.
List< State > metaheuristics.generators.DistributionEstimationAlgorithm.getfathersList()
getfathersList - method to get the list of father states.
returns the list of father states.
References metaheuristics.generators.DistributionEstimationAlgorithm.iffatherselection, evolutionary_algorithms.complement.FatherSelection.selection, metaheuristics.generators.DistributionEstimationAlgorithm.selectionType, metaheuristics.generators.DistributionEstimationAlgorithm.truncation.
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.generate.
List< State > metaheuristics.generators.DistributionEstimationAlgorithm.getSonList()
getSonList - method to get the list of son states.
returns the list of son states.
References metaheuristics.generators.DistributionEstimationAlgorithm.sonList.
boolean metaheuristics.generators.DistributionEstimationAlgorithm.awardUpdateREF(State stateCandidate)
awardUpdateREF - method to award the update of the reference state.
stateCandidate returns true if the candidate state is already in the reference list, false otherwise.
float metaheuristics.generators.DistributionEstimationAlgorithm.getWeight()
getWeight - method to get the weight.
returns the weight.
void metaheuristics.generators.DistributionEstimationAlgorithm.setWeight(float weight)
setWeight - method to set the weight.
weight
References metaheuristics.generators.DistributionEstimationAlgorithm.weight.
DistributionType metaheuristics.generators.DistributionEstimationAlgorithm.getDistributionType()
getDistributionType - method to get the distribution type.
returns the distribution type.
References metaheuristics.generators.DistributionEstimationAlgorithm.distributionType.
void metaheuristics.generators.DistributionEstimationAlgorithm.setDistributionType(DistributionType distributionType)
setDistributionType - method to set the distribution type.
distributionType the distribution type to set
References metaheuristics.generators.DistributionEstimationAlgorithm.distributionType.
int[] metaheuristics.generators.DistributionEstimationAlgorithm.getListCountBetterGender()
getListCountBetterGender - method to get the list of count better gender.
returns the list of count better gender.
int[] metaheuristics.generators.DistributionEstimationAlgorithm.getListCountGender()
getListCountGender - method to get the list of count gender.
returns the list of count gender.
float[] metaheuristics.generators.DistributionEstimationAlgorithm.getTrace()
getTrace - method to get the trace.
returns the trace.