metaheuristics::generators::MultiGenerator
GeneratorType metaheuristics.generators.MultiGenerator.generatortype
Referenced by metaheuristics.generators.MultiGenerator.setGeneratorType.
Generator [] metaheuristics.generators.MultiGenerator.listGenerators
Referenced by metaheuristics.generators.MultiGenerator.destroyMultiGenerator, metaheuristics.generators.MultiGenerator.getListGenerators, metaheuristics.generators.MultiGenerator.initializeGenerators, metaheuristics.generators.MultiGenerator.initializeListGenerator, metaheuristics.generators.MultiGenerator.roulette, metaheuristics.generators.MultiGenerator.setListGenerators, metaheuristics.generators.MultiGenerator.tournament, metaheuristics.generators.MultiGenerator.updateAwardImp, metaheuristics.generators.MultiGenerator.updateAwardSC.
final Logger metaheuristics.generators.MultiGenerator.LOGGER
Referenced by metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP.
final List<State> metaheuristics.generators.MultiGenerator.listGeneratedPP
Referenced by metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, metaheuristics.generators.MultiGenerator.destroyMultiGenerator, metaheurictics.strategy.Strategy.executeStrategy, metaheuristics.generators.MultiGenerator.getListGeneratedPP, metaheuristics.generators.MultiGenerator.setListGeneratedPP.
volatile Generator metaheuristics.generators.MultiGenerator.activeGenerator
Referenced by metaheuristics.generators.MultiGenerator.destroyMultiGenerator, metaheuristics.generators.MultiGenerator.generate, metaheuristics.generators.MultiGenerator.getActiveGenerator, metaheuristics.generators.MultiGenerator.searchState, metaheuristics.generators.MultiGenerator.setActiveGenerator, metaheuristics.generators.MultiGenerator.updateAwardImp, metaheuristics.generators.MultiGenerator.updateAwardSC.
final List<State> metaheuristics.generators.MultiGenerator.listStateReference
Referenced by metaheuristics.generators.MultiGenerator.destroyMultiGenerator, metaheuristics.generators.MultiGenerator.getReferenceList, metaheuristics.generators.MultiGenerator.initializeGenerators, metaheurictics.strategy.Strategy.updateRef.
void metaheuristics.generators.MultiGenerator.setGeneratorType(GeneratorType generatortype)
setGeneratorType - set the type of the generator.
generatortype the type of the generator to set
References metaheuristics.generators.MultiGenerator.generatortype.
metaheuristics.generators.MultiGenerator.MultiGenerator()
MultiGenerator - default constructor.
References metaheuristics.generators.GeneratorType.MultiGenerator.
Referenced by metaheuristics.generators.MultiGenerator.clone, metaheuristics.generators.MultiGenerator.generate, metaheuristics.generators.MultiGenerator.initializeGenerators, metaheuristics.generators.MultiGenerator.tournament.
State metaheuristics.generators.MultiGenerator.generate(Integer operatornumber)
generate - generate a new state using the MultiGenerator.
operatornumber IllegalArgumentException SecurityException ClassNotFoundException InstantiationException IllegalAccessException InvocationTargetException NoSuchMethodException
References metaheuristics.generators.MultiGenerator.activeGenerator, metaheuristics.generators.Generator.generate, metaheurictics.strategy.Strategy.generator, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.MultiGenerator.MultiGenerator, metaheuristics.generators.MultiGenerator.roulette.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
State metaheuristics.generators.MultiGenerator.getReference()
getReference - get the reference state.
the reference state
List< State > metaheuristics.generators.MultiGenerator.getReferenceList()
getReferenceList - get the list of reference states.
the list of reference states
References metaheuristics.generators.MultiGenerator.listStateReference.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
List< State > metaheuristics.generators.MultiGenerator.getSonList()
getSonList - get the list of son states.
the list of son states
GeneratorType metaheuristics.generators.MultiGenerator.getType()
getType - get the type of the generator.
the type of the generator
Referenced by metaheuristics.generators.MultiGenerator.initializeGenerators, metaheuristics.generators.MultiGenerator.tournament, metaheuristics.generators.MultiGenerator.updateAwardImp, metaheuristics.generators.MultiGenerator.updateAwardSC.
void metaheuristics.generators.MultiGenerator.setInitialReference(State stateInitialRef)
setInitialReference - set the initial reference state.
stateInitialRef the initial reference state
void metaheuristics.generators.MultiGenerator.updateReference(State stateCandidate, Integer countIterationsCurrent)
References metaheuristics.generators.MultiGenerator.tournament, metaheuristics.generators.MultiGenerator.updateWeight.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
void metaheuristics.generators.MultiGenerator.updateWeight(State stateCandidate)
updateWeight - modify the weight of the generator.
stateCandidate
References metaheuristics.generators.MultiGenerator.searchState, metaheuristics.generators.MultiGenerator.updateAwardImp, metaheuristics.generators.MultiGenerator.updateAwardSC.
Referenced by metaheuristics.generators.MultiGenerator.updateReference.
boolean metaheuristics.generators.MultiGenerator.searchState(State stateCandidate)
searchState - search for a state in the reference list.
stateCandidate return true if the state is found, false otherwise
References metaheuristics.generators.MultiGenerator.activeGenerator, metaheurictics.strategy.Strategy.getBestState, problem.definition.State.getEvaluation, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, problem.definition.Problem.getTypeProblem, problem.definition.Problem.ProblemType.Maximizar.
Referenced by metaheuristics.generators.MultiGenerator.updateWeight.
float metaheuristics.generators.MultiGenerator.getWeight()
getWeight - get the weight of the generator.
the weight of the generator
Generator metaheuristics.generators.MultiGenerator.roulette()
roulette - select a generator using roulette wheel selection.
the selected generator
References metaheuristics.generators.MultiGenerator.listGenerators, metaheuristics.generators.LimitRoulette.setGenerator, metaheuristics.generators.LimitRoulette.setLimitHigh, metaheuristics.generators.LimitRoulette.setLimitLow.
Referenced by metaheuristics.generators.MultiGenerator.generate.
boolean metaheuristics.generators.MultiGenerator.awardUpdateREF(State stateCandidate)
awardUpdateREF - update the reference of the generator.
stateCandidate return true if the reference was updated, false otherwise
void metaheuristics.generators.MultiGenerator.updateAwardSC()
updateAwardSC - update the award for the selected generator.
References metaheuristics.generators.MultiGenerator.activeGenerator, metaheurictics.strategy.Strategy.getCountCurrent, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.MultiGenerator.getType, metaheuristics.generators.MultiGenerator.listGenerators, metaheuristics.generators.GeneratorType.MultiGenerator, metaheuristics.generators.MultiGenerator.updateAwardSC.
Referenced by metaheuristics.generators.MultiGenerator.updateAwardSC, metaheuristics.generators.MultiGenerator.updateWeight.
void metaheuristics.generators.MultiGenerator.updateAwardImp()
updateAwardImp - update the award for the selected generator.
References metaheuristics.generators.MultiGenerator.activeGenerator, metaheurictics.strategy.Strategy.getCountCurrent, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.MultiGenerator.getType, metaheuristics.generators.MultiGenerator.listGenerators, metaheuristics.generators.GeneratorType.MultiGenerator, metaheuristics.generators.MultiGenerator.updateAwardImp.
Referenced by metaheuristics.generators.MultiGenerator.updateAwardImp, metaheuristics.generators.MultiGenerator.updateWeight.
void metaheuristics.generators.MultiGenerator.setWeight(float weight)
setWeight - set the weight of the generator.
weight
float[] metaheuristics.generators.MultiGenerator.getTrace()
getTrace - get the trace of the generator.
the trace array
void metaheuristics.generators.MultiGenerator.tournament(State stateCandidate, Integer countIterationsCurrent)
tournament - update the tournament for the selected generator.
stateCandidate countIterationsCurrent
References metaheuristics.generators.MultiGenerator.getType, metaheuristics.generators.MultiGenerator.listGenerators, metaheuristics.generators.GeneratorType.MultiGenerator, metaheuristics.generators.MultiGenerator.MultiGenerator, metaheuristics.generators.MultiGenerator.tournament.
Referenced by metaheuristics.generators.MultiGenerator.tournament, metaheuristics.generators.MultiGenerator.updateReference.
Object metaheuristics.generators.MultiGenerator.clone()
clone - create a copy of the generator.
a clone of the generator
References metaheuristics.generators.MultiGenerator.MultiGenerator.
int[] metaheuristics.generators.MultiGenerator.getListCountBetterGender()
getListCountBetterGender - get the list of counts for better gender.
the list of counts for better gender
int[] metaheuristics.generators.MultiGenerator.getListCountGender()
getListCountGender - get the list of counts for gender.
the list of counts for gender
static void metaheuristics.generators.MultiGenerator.destroyMultiGenerator()
destroyMultiGenerator - destroy the MultiGenerator instance.
References metaheuristics.generators.MultiGenerator.activeGenerator, metaheuristics.generators.MultiGenerator.listGeneratedPP, metaheuristics.generators.MultiGenerator.listGenerators, metaheuristics.generators.MultiGenerator.listStateReference.
static void metaheuristics.generators.MultiGenerator.initializeListGenerator()
initializeListGenerator - initialize the list of generators.
IllegalArgumentException SecurityException ClassNotFoundException InstantiationException IllegalAccessException InvocationTargetException NoSuchMethodException
References metaheuristics.generators.MultiGenerator.listGenerators.
Referenced by metaheuristics.generators.MultiGenerator.initializeGenerators.
static void metaheuristics.generators.MultiGenerator.initializeGenerators()
initializeGenerators - initialize the generators. IllegalArgumentException SecurityException ClassNotFoundException InstantiationException IllegalAccessException InvocationTargetException NoSuchMethodException
References factory_method.FactoryGenerator.createGenerator, metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, metaheuristics.generators.GeneratorType.DistributionEstimationAlgorithm, metaheuristics.generators.GeneratorType.EvolutionStrategies, metaheuristics.generators.GeneratorType.GeneticAlgorithm, metaheurictics.strategy.Strategy.getProblem, problem.definition.Problem.getState, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.MultiGenerator.getType, metaheuristics.generators.GeneratorType.HillClimbing, metaheuristics.generators.MultiGenerator.initializeListGenerator, metaheuristics.generators.GeneratorType.LimitThreshold, metaheuristics.generators.MultiGenerator.listGenerators, metaheuristics.generators.MultiGenerator.listStateReference, metaheurictics.strategy.Strategy.listStates, metaheuristics.generators.MultiGenerator.MultiGenerator, metaheuristics.generators.GeneratorType.RandomSearch, metaheuristics.generators.GeneratorType.SimulatedAnnealing, metaheuristics.generators.GeneratorType.TabuSearch.
Referenced by metaheurictics.strategy.Strategy.executeStrategy.
static void metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP()
createInstanceGeneratorsBPP - create instances of generators for the BPP problem.
References metaheuristics.generators.EvolutionStrategies.countRef, problem.definition.Problem.Evaluate, metaheuristics.generators.Generator.generate, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.Generator.getType, metaheuristics.generators.MultiGenerator.listGeneratedPP, metaheuristics.generators.MultiGenerator.LOGGER, problem.definition.State.setNumber, problem.definition.State.setTypeGenerator.
Referenced by metaheuristics.generators.MultiGenerator.initializeGenerators.
static Generator[] metaheuristics.generators.MultiGenerator.getListGenerators()
getListGenerators - get the list of generators.
the list of generators
References metaheuristics.generators.MultiGenerator.listGenerators.
Referenced by metaheuristics.generators.InstanceDE.run, metaheuristics.generators.InstanceEE.run, metaheuristics.generators.InstanceGA.run, metaheurictics.strategy.Strategy.updateCountGender, metaheurictics.strategy.Strategy.updateRefMultiG, metaheurictics.strategy.Strategy.updateWeight.
static void metaheuristics.generators.MultiGenerator.setListGenerators(Generator[] listGenerators)
setListGenerators - set the list of generators.
listGenerators the list of generators to set
References metaheuristics.generators.MultiGenerator.listGenerators.
static Generator metaheuristics.generators.MultiGenerator.getActiveGenerator()
getActiveGenerator - get the active generator.
the active generator
References metaheuristics.generators.MultiGenerator.activeGenerator.
static void metaheuristics.generators.MultiGenerator.setActiveGenerator(Generator activeGenerator)
setActiveGenerator - set the active generator.
activeGenerator the active generator to set
References metaheuristics.generators.MultiGenerator.activeGenerator.
static void metaheuristics.generators.MultiGenerator.setListGeneratedPP(List< State > newListGeneratedPP)
setListGeneratedPP - set the list of generated states for the PP problem.
newListGeneratedPP the new list of generated states
References metaheuristics.generators.MultiGenerator.listGeneratedPP.
static List< State > metaheuristics.generators.MultiGenerator.getListGeneratedPP()
getListGeneratedPP - get the list of generated states for the PP problem.
the list of generated states
References metaheuristics.generators.MultiGenerator.listGeneratedPP.