evolutionary_algorithms::complement::Replace
abstract List< State > evolutionary_algorithms.complement.Replace.replace(State stateCandidate, List< State >listState)
replace - replace the worst individual in the population.
stateCandidate listState IllegalArgumentException SecurityException ClassNotFoundException InstantiationException IllegalAccessException InvocationTargetException NoSuchMethodException
Referenced by metaheuristics.generators.DistributionEstimationAlgorithm.updateReference, metaheuristics.generators.EvolutionStrategies.updateReference, metaheuristics.generators.GeneticAlgorithm.updateReference.