factory_method::FactoryLoader
static Object factory_method.FactoryLoader.getInstance(String className)
FactoryLoader - Carga dinámicamente una clase por su nombre y crea una instancia.
className ClassNotFoundException IllegalArgumentException SecurityException InstantiationException IllegalAccessException InvocationTargetException NoSuchMethodException
Referenced by factory_method.FactoryAcceptCandidate.createAcceptCandidate, factory_method.FactoryCrossover.createCrossover, factory_method.FactoryDistribution.createDistribution, factory_method.FactorySolutionMethod.createdSolutionMethod, factory_method.FactoryGenerator.createGenerator, factory_method.FactoryMutation.createMutation, factory_method.FactoryReplace.createReplace, factory_method.FactorySampling.createSampling, factory_method.FactoryCandidate.createSearchCandidate, factory_method.FactoryFatherSelection.createSelectFather.