local_search::acceptation_type::Dominance
boolean local_search.acceptation_type.Dominance.listDominance(State solutionX, List< State > list)
Check whether solutionX dominates members of the supplied list and update the list accordingly.
If solutionX is not dominated and not present it is added. solutionX the candidate solution to test list the list of non-dominated solutions (Pareto front) true if the solution was added to the list (i.e. it is non-dominated and not duplicate), false otherwise
References problem.definition.State.clone, problem.definition.State.Comparator, metaheuristics.generators.MultiobjectiveHillClimbingDistance.distanceCalculateAdd, local_search.acceptation_type.Dominance.dominance, metaheurictics.strategy.Strategy.generator, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.Generator.getType, metaheuristics.generators.GeneratorType.MultiobjectiveHillClimbingDistance.
Referenced by local_search.acceptation_type.AcceptMulticase.acceptCandidate, local_search.acceptation_type.AcceptNotDominated.acceptCandidate, local_search.acceptation_type.AcceptNotDominatedTabu.acceptCandidate.
boolean local_search.acceptation_type.Dominance.dominance(State solutionX, State solutionY)
Determine whether solutionX Pareto-dominates solutionY.
solutionX the candidate solution solutionY the reference solution true if solutionX dominates solutionY according to the problem objective type, false otherwise
References local_search.acceptation_type.Dominance.dominance, problem.definition.State.getEvaluation, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, problem.definition.Problem.getTypeProblem, problem.definition.Problem.ProblemType.Maximizar.
Referenced by local_search.acceptation_type.AcceptMulticase.acceptCandidate, local_search.acceptation_type.AcceptNotDominated.acceptCandidate, local_search.acceptation_type.Dominance.dominance, local_search.acceptation_type.AcceptMulticase.dominanceCounter, local_search.acceptation_type.AcceptMulticase.dominanceRank, local_search.acceptation_type.Dominance.listDominance, local_search.candidate_type.NotDominatedCandidate.stateSearch.