metaheuristics::generators::EvolutionStrategies
State metaheuristics.generators.EvolutionStrategies.stateReferenceES
Referenced by metaheuristics.generators.EvolutionStrategies.getReference.
List<State> metaheuristics.generators.EvolutionStrategies.listStateReference
Referenced by metaheuristics.generators.EvolutionStrategies.generate, metaheuristics.generators.EvolutionStrategies.getListStateRef, metaheuristics.generators.EvolutionStrategies.getListStateReference, metaheuristics.generators.EvolutionStrategies.getReference, metaheuristics.generators.EvolutionStrategies.getReferenceList, metaheuristics.generators.EvolutionStrategies.setListStateReference, metaheuristics.generators.EvolutionStrategies.updateReference.
IFFactoryFatherSelection metaheuristics.generators.EvolutionStrategies.iffatherselection
Referenced by metaheuristics.generators.EvolutionStrategies.generate.
IFFactoryMutation metaheuristics.generators.EvolutionStrategies.iffactorymutation
Referenced by metaheuristics.generators.EvolutionStrategies.generate.
IFFactoryReplace metaheuristics.generators.EvolutionStrategies.iffreplace
Referenced by metaheuristics.generators.EvolutionStrategies.updateReference.
GeneratorType metaheuristics.generators.EvolutionStrategies.generatorType
Referenced by metaheuristics.generators.EvolutionStrategies.getType, metaheuristics.generators.EvolutionStrategies.getTypeGenerator, metaheuristics.generators.EvolutionStrategies.setTypeGenerator.
float metaheuristics.generators.EvolutionStrategies.weight
Referenced by metaheuristics.generators.EvolutionStrategies.setWeight.
int [] metaheuristics.generators.EvolutionStrategies.listCountBetterGender
Referenced by metaheuristics.generators.EvolutionStrategies.EvolutionStrategies.
int [] metaheuristics.generators.EvolutionStrategies.listCountGender
Referenced by metaheuristics.generators.EvolutionStrategies.EvolutionStrategies.
float [] metaheuristics.generators.EvolutionStrategies.listTrace
Referenced by metaheuristics.generators.EvolutionStrategies.EvolutionStrategies.
final double metaheuristics.generators.EvolutionStrategies.PM
Referenced by metaheuristics.generators.EvolutionStrategies.generate.
final MutationType metaheuristics.generators.EvolutionStrategies.mutationType
Referenced by metaheuristics.generators.EvolutionStrategies.generate.
final ReplaceType metaheuristics.generators.EvolutionStrategies.replaceType
Referenced by metaheuristics.generators.EvolutionStrategies.updateReference.
final SelectionType metaheuristics.generators.EvolutionStrategies.selectionType
Referenced by metaheuristics.generators.EvolutionStrategies.generate.
final int metaheuristics.generators.EvolutionStrategies.countRef
Referenced by metaheuristics.generators.MultiGenerator.createInstanceGeneratorsBPP, metaheuristics.generators.RandomSearch.generate, metaheurictics.strategy.Strategy.update, local_search.complement.UpdateParameter.updateParameter.
final int metaheuristics.generators.EvolutionStrategies.truncation
Referenced by metaheuristics.generators.EvolutionStrategies.generate.
metaheuristics.generators.EvolutionStrategies.EvolutionStrategies()
EvolutionStrategies - method to create an instance of EvolutionStrategies.
References metaheuristics.generators.GeneratorType.EvolutionStrategies, metaheuristics.generators.EvolutionStrategies.getListStateRef, metaheuristics.generators.EvolutionStrategies.listCountBetterGender, metaheuristics.generators.EvolutionStrategies.listCountGender, metaheuristics.generators.EvolutionStrategies.listTrace.
Referenced by metaheuristics.generators.EvolutionStrategies.getListStateRef.
State metaheuristics.generators.EvolutionStrategies.generate(Integer operatornumber)
Uses ThreadLocalRandom for algorithmic (non-cryptographic) randomness.
This RNG is used to decide whether a mutation occurs in the evolutionary algorithm and is not used for security-sensitive purposes. Suppress Sonar security hotspot S2245 for this usage. generate - method to generate a new state. operatornumber returns the generated state.
References problem.definition.State.getCopy, metaheurictics.strategy.Strategy.getProblem, problem.definition.Problem.getState, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.EvolutionStrategies.iffactorymutation, metaheuristics.generators.EvolutionStrategies.iffatherselection, metaheuristics.generators.EvolutionStrategies.listStateReference, evolutionary_algorithms.complement.Mutation.mutation, metaheuristics.generators.EvolutionStrategies.mutationType, metaheuristics.generators.EvolutionStrategies.PM, evolutionary_algorithms.complement.FatherSelection.selection, metaheuristics.generators.EvolutionStrategies.selectionType, problem.definition.State.setCode, problem.definition.State.setEvaluation, problem.definition.State.setNumber, problem.definition.State.setTypeGenerator, metaheuristics.generators.EvolutionStrategies.truncation.
State metaheuristics.generators.EvolutionStrategies.getReference()
getReference - method to get the current reference state.
returns the current reference state.
References metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, problem.definition.Problem.getTypeProblem, metaheuristics.generators.EvolutionStrategies.listStateReference, problem.definition.Problem.ProblemType.Maximizar, metaheuristics.generators.EvolutionStrategies.stateReferenceES.
void metaheuristics.generators.EvolutionStrategies.setStateRef(State stateRef)
setStateRef - method to set the current reference state.
stateRef
GeneratorType metaheuristics.generators.EvolutionStrategies.getType()
getType - method to get the generator type.
returns the generator type.
References metaheuristics.generators.EvolutionStrategies.generatorType.
void metaheuristics.generators.EvolutionStrategies.setInitialReference(State stateInitialRef)
setInitialReference - method to set the initial reference state.
stateInitialRef
void metaheuristics.generators.EvolutionStrategies.updateReference(State stateCandidate, Integer countIterationsCurrent)
updateReference - method to update the reference state.
stateCandidate countIterationsCurrent
References metaheuristics.generators.EvolutionStrategies.iffreplace, metaheuristics.generators.EvolutionStrategies.listStateReference, evolutionary_algorithms.complement.Replace.replace, metaheuristics.generators.EvolutionStrategies.replaceType.
List< State > metaheuristics.generators.EvolutionStrategies.getListStateRef()
getListStateRef - method to get the list of reference states.
returns the list of reference states.
References metaheuristics.generators.EvolutionStrategies.EvolutionStrategies, metaheuristics.generators.GeneratorType.EvolutionStrategies, metaheurictics.strategy.Strategy.getListKey, metaheuristics.generators.EvolutionStrategies.getListStateReference, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.EvolutionStrategies.listStateReference, metaheuristics.generators.RandomSearch.listStateReference, metaheurictics.strategy.Strategy.mapGenerators.
Referenced by metaheuristics.generators.EvolutionStrategies.EvolutionStrategies.
List< State > metaheuristics.generators.EvolutionStrategies.getListStateReference()
getListStateReference - method to get the list of reference states.
returns the list of reference states.
References metaheuristics.generators.EvolutionStrategies.listStateReference.
Referenced by metaheuristics.generators.EvolutionStrategies.getListStateRef.
void metaheuristics.generators.EvolutionStrategies.setListStateReference(List< State > listStateReference)
setListStateReference - method to set the list of reference states.
listStateReference
References metaheuristics.generators.EvolutionStrategies.listStateReference.
GeneratorType metaheuristics.generators.EvolutionStrategies.getTypeGenerator()
getTypeGenerator - method to get the generator type.
returns the generator type.
References metaheuristics.generators.EvolutionStrategies.generatorType.
void metaheuristics.generators.EvolutionStrategies.setTypeGenerator(GeneratorType generatorType)
setTypeGenerator - method to set the generator type.
generatorType
References metaheuristics.generators.EvolutionStrategies.generatorType.
List< State > metaheuristics.generators.EvolutionStrategies.getReferenceList()
getReferenceList - method to get the list of reference states.
returns the list of reference states.
References metaheuristics.generators.EvolutionStrategies.listStateReference.
List< State > metaheuristics.generators.EvolutionStrategies.getSonList()
getSonList - method to get the list of son states.
returns the list of son states.
boolean metaheuristics.generators.EvolutionStrategies.awardUpdateREF(State stateCandidate)
awardUpdateREF - method to award the update of the reference state.
stateCandidate returns true if the update is awarded, false otherwise.
float metaheuristics.generators.EvolutionStrategies.getWeight()
getWeight - method to get the weight.
returns the weight.
void metaheuristics.generators.EvolutionStrategies.setWeight(float weight)
setWeight - method to set the weight.
weight
References metaheuristics.generators.EvolutionStrategies.weight.
int[] metaheuristics.generators.EvolutionStrategies.getListCountBetterGender()
getListCountBetterGender - method to get the list of count better gender.
int[] metaheuristics.generators.EvolutionStrategies.getListCountGender()
getListCountGender - method to get the list of count gender.
returns the list of count gender.
float[] metaheuristics.generators.EvolutionStrategies.getTrace()
getTrace - method to get the trace.
returns the trace.