metaheuristics::generators::SimulatedAnnealing
CandidateValue metaheuristics.generators.SimulatedAnnealing.candidatevalue
Referenced by metaheuristics.generators.SimulatedAnnealing.generate.
AcceptType metaheuristics.generators.SimulatedAnnealing.typeAcceptation
Referenced by metaheuristics.generators.SimulatedAnnealing.updateReference.
StrategyType metaheuristics.generators.SimulatedAnnealing.strategy
Referenced by metaheuristics.generators.SimulatedAnnealing.generate.
CandidateType metaheuristics.generators.SimulatedAnnealing.typeCandidate
Referenced by metaheuristics.generators.SimulatedAnnealing.generate.
State metaheuristics.generators.SimulatedAnnealing.stateReferenceSA
Referenced by metaheuristics.generators.SimulatedAnnealing.generate, metaheuristics.generators.SimulatedAnnealing.getReference, metaheuristics.generators.SimulatedAnnealing.getReferenceList, metaheuristics.generators.SimulatedAnnealing.updateReference.
IFFactoryAcceptCandidate metaheuristics.generators.SimulatedAnnealing.ifacceptCandidate
Referenced by metaheuristics.generators.SimulatedAnnealing.updateReference.
int metaheuristics.generators.SimulatedAnnealing.countRept
Referenced by metaheuristics.generators.SimulatedAnnealing.updateReference.
GeneratorType metaheuristics.generators.SimulatedAnnealing.typeGenerator
Referenced by metaheuristics.generators.SimulatedAnnealing.getTypeGenerator, metaheuristics.generators.SimulatedAnnealing.setTypeGenerator.
List<State> metaheuristics.generators.SimulatedAnnealing.listStateReference
Referenced by metaheuristics.generators.SimulatedAnnealing.getReferenceList.
float metaheuristics.generators.SimulatedAnnealing.weight
Referenced by metaheuristics.generators.SimulatedAnnealing.getWeight, metaheuristics.generators.SimulatedAnnealing.setWeight, metaheuristics.generators.SimulatedAnnealing.SimulatedAnnealing.
int [] metaheuristics.generators.SimulatedAnnealing.listCountBetterGender
Referenced by metaheuristics.generators.SimulatedAnnealing.getListCountBetterGender, metaheuristics.generators.SimulatedAnnealing.SimulatedAnnealing.
int [] metaheuristics.generators.SimulatedAnnealing.listCountGender
Referenced by metaheuristics.generators.SimulatedAnnealing.getListCountGender, metaheuristics.generators.SimulatedAnnealing.SimulatedAnnealing.
float [] metaheuristics.generators.SimulatedAnnealing.listTrace
Referenced by metaheuristics.generators.SimulatedAnnealing.getTrace, metaheuristics.generators.SimulatedAnnealing.SimulatedAnnealing.
final double metaheuristics.generators.SimulatedAnnealing.alpha
Referenced by metaheuristics.generators.SimulatedAnnealing.updateReference.
final Double metaheuristics.generators.SimulatedAnnealing.tfinal
Double metaheuristics.generators.SimulatedAnnealing.tinitial
Referenced by metaheuristics.generators.SimulatedAnnealing.getTinitial, metaheuristics.generators.SimulatedAnnealing.setTinitial.
int metaheuristics.generators.SimulatedAnnealing.countIterationsT
static int metaheuristics.generators.SimulatedAnnealing.getCountIterationsT()
getCountIterationsT - get the count of iterations for temperature update.
the count of iterations for temperature update
Referenced by metaheuristics.generators.SimulatedAnnealing.updateReference.
static void metaheuristics.generators.SimulatedAnnealing.setCountIterationsT(int c)
setCountIterationsT - set the count of iterations for temperature update.
c the count of iterations to set
static Double metaheuristics.generators.SimulatedAnnealing.getTinitial()
Getter for initial temperature.
References metaheuristics.generators.SimulatedAnnealing.tinitial.
Referenced by local_search.acceptation_type.AcceptNotBadT.acceptCandidate.
static void metaheuristics.generators.SimulatedAnnealing.setTinitial(Double t)
Setter for initial temperature.
References metaheuristics.generators.SimulatedAnnealing.tinitial.
GeneratorType metaheuristics.generators.SimulatedAnnealing.getTypeGenerator()
getTypeGenerator - get the type of the generator.
the type of the generator
References metaheuristics.generators.SimulatedAnnealing.typeGenerator.
void metaheuristics.generators.SimulatedAnnealing.setTypeGenerator(GeneratorType typeGenerator)
setTypeGenerator - set the type of the generator.
typeGenerator
References metaheuristics.generators.SimulatedAnnealing.typeGenerator.
metaheuristics.generators.SimulatedAnnealing.SimulatedAnnealing()
SimulatedAnnealing - descripcion (añade detalles).
References local_search.acceptation_type.AcceptType.AcceptNotBadT, metaheuristics.generators.SimulatedAnnealing.listCountBetterGender, metaheuristics.generators.SimulatedAnnealing.listCountGender, metaheuristics.generators.SimulatedAnnealing.listTrace, local_search.complement.StrategyType.NORMAL, local_search.candidate_type.CandidateType.RandomCandidate, metaheuristics.generators.GeneratorType.SimulatedAnnealing, metaheuristics.generators.SimulatedAnnealing.weight.
Referenced by metaheuristics.generators.SimulatedAnnealing.updateReference.
State metaheuristics.generators.SimulatedAnnealing.generate(Integer operatornumber)
generate - method to generate a new state.
operatornumber return the generated state
References metaheuristics.generators.SimulatedAnnealing.candidatevalue, problem.definition.Operator.generatedNewState, problem.definition.Problem.getOperator, metaheurictics.strategy.Strategy.getProblem, metaheurictics.strategy.Strategy.getStrategy, metaheuristics.generators.SimulatedAnnealing.stateReferenceSA, metaheuristics.generators.SimulatedAnnealing.strategy, metaheuristics.generators.SimulatedAnnealing.typeCandidate.
State metaheuristics.generators.SimulatedAnnealing.getReference()
getReference - get the reference state.
the reference state
References metaheuristics.generators.SimulatedAnnealing.stateReferenceSA.
void metaheuristics.generators.SimulatedAnnealing.setStateRef(State stateRef)
setStateRef - set the reference state.
stateRef the reference state to set
void metaheuristics.generators.SimulatedAnnealing.setInitialReference(State stateInitialRef)
setInitialReference - set the initial reference state.
stateInitialRef the initial reference state to set
void metaheuristics.generators.SimulatedAnnealing.updateReference(State stateCandidate, Integer countIterationsCurrent)
updateReference - update the reference state.
stateCandidate countIterationsCurrent
References local_search.acceptation_type.AcceptableCandidate.acceptCandidate, metaheuristics.generators.SimulatedAnnealing.alpha, metaheuristics.generators.SimulatedAnnealing.countRept, metaheuristics.generators.SimulatedAnnealing.getCountIterationsT, metaheuristics.generators.SimulatedAnnealing.ifacceptCandidate, metaheuristics.generators.SimulatedAnnealing.SimulatedAnnealing, metaheuristics.generators.SimulatedAnnealing.stateReferenceSA, metaheuristics.generators.SimulatedAnnealing.typeAcceptation.
GeneratorType metaheuristics.generators.SimulatedAnnealing.getType()
getType - get the type of the generator.
the type of the generator
List< State > metaheuristics.generators.SimulatedAnnealing.getReferenceList()
getReferenceList - get the list of reference states.
the list of reference states
References metaheuristics.generators.SimulatedAnnealing.listStateReference, metaheuristics.generators.SimulatedAnnealing.stateReferenceSA.
List< State > metaheuristics.generators.SimulatedAnnealing.getSonList()
getSonList - get the list of child states.
the list of child states
boolean metaheuristics.generators.SimulatedAnnealing.awardUpdateREF(State stateCandidate)
awardUpdateREF - award the update of the reference state.
stateCandidate return true if the update is awarded, false otherwise
float metaheuristics.generators.SimulatedAnnealing.getWeight()
getWeight - get the weight of the generator.
the weight of the generator
References metaheuristics.generators.SimulatedAnnealing.weight.
void metaheuristics.generators.SimulatedAnnealing.setWeight(float weight)
setWeight - set the weight of the generator.
weight the weight to set
References metaheuristics.generators.SimulatedAnnealing.weight.
int[] metaheuristics.generators.SimulatedAnnealing.getListCountBetterGender()
getListCountBetterGender - get the list of better gender counts.
the list of better gender counts
References metaheuristics.generators.SimulatedAnnealing.listCountBetterGender.
int[] metaheuristics.generators.SimulatedAnnealing.getListCountGender()
getListCountGender - get the list of gender counts.
the list of gender counts
References metaheuristics.generators.SimulatedAnnealing.listCountGender.
float[] metaheuristics.generators.SimulatedAnnealing.getTrace()
getTrace -get the trace of the generator.
the trace of the generator
References metaheuristics.generators.SimulatedAnnealing.listTrace.